#!/bin/bash -e

if [[ "$OSTYPE" == "linux-gnu" ]]; then
	echo "Building init (stage1)..."
	go build -o bin/init ./stage1/init

	S1INIT=stage0/stage1_init
	if [ bin/init -nt $S1INIT/bin.go ]; then
		echo "Packaging init (stage1)..."
		TMP=$(mktemp -d -t rocket-XXXXXX)
		[ -d $S1INIT ] || mkdir -p $S1INIT
		cp bin/init $TMP/s1init
		go-bindata -o $S1INIT/bin.go -pkg="stage1_init" -prefix=$TMP $TMP
	fi

	echo "Building rootfs (stage1)..."
	make -C stage1/rootfs
fi

echo "Building rkt (stage0)..."
go build -o bin/rkt ./rkt

echo "Building metadatasvc..."
go build -o bin/metadatasvc ./metadatasvc
