#!/bin/bash -e

REPO_PATH="github.com/coreos-inc/rkt"

GOBIN=${PWD}/bin

echo "Building rkt (stage0)..."
godep go build -o $GOBIN/rkt ${REPO_PATH}/stage0

echo "Building init (stage1)..."
godep go build -o $GOBIN/init ${REPO_PATH}/stage1

echo "Building metadatasvc..."
godep go build -o $GOBIN/metadatasvc ${REPO_PATH}/metadatasvc
