#!/bin/sh
#
# Run all rocket tests
# ./test
# ./test -v
#
# Run tests for one package
#
# PKG=./cas ./test
# PKG=cas ./test

# Invoke ./cover for HTML output
COVER=${COVER:-"-cover"}

. ./build

TESTABLE_AND_FORMATTABLE="cas pkg/tar"
FORMATTABLE="$TESTABLE_AND_FORMATTABLE metadatasvc path pkg/io pkg/proc rkt stage0/run.go stage1 version"

# user has not provided PKG override
if [ -z "$PKG" ]; then
	TEST=$TESTABLE_AND_FORMATTABLE
	FMT=$FORMATTABLE

# user has provided PKG override
else
	# strip out leading dotslashes and trailing slashes from PKG=./foo/
  TEST=$(echo " $PKG" | sed -E 's:\s+\./: :g')

	# only run gofmt on packages provided by user
	FMT="$TEST"
fi

TEST=$(echo " $TEST" | sed -E 's:\s+: '$REPO_PATH'/:g')

echo "Running tests..."
go test -timeout 60s ${COVER} $@ ${TEST} --race

echo "Checking gofmt..."
fmtRes=$(gofmt -l $FMT)
if [ -n "${fmtRes}" ]; then
	echo -e "gofmt checking failed:\n${fmtRes}"
	exit 255
fi

echo "Checking govet..."
vetRes=$(go vet $TEST)
if [ -n "${vetRes}" ]; then
	echo -e "govet checking failed:\n${vetRes}"
	exit 255
fi

echo "Success"
