#!/bin/bash -e

# Derive a minimal rootfs for hosting systemd from a coreos release pxe image
# This is only done when we need to update ../cmd/s1rootfs.go

IMG_RELEASE="444.5.0"
IMG_URL="http://stable.release.core-os.net/amd64-usr/${IMG_RELEASE}/coreos_production_pxe_image.cpio.gz"

function req() {
	what=$1

	which "${what}" >/dev/null || { echo "${what} required"; exit 1; }
}

req cpio
req curl
req gcc
req go-bindata
req gpg
req gzip
req install
req mktemp
req tar
req unsquashfs

# coreos gpg signing key
GPG_LONG_ID="50E0885593D2DCB4"
GPG_KEY="-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQINBFIqVhQBEADjC7oxg5N9Xqmqqrac70EHITgjEXZfGm7Q50fuQlqDoeNWY+sN
szpw//dWz8lxvPAqUlTSeR+dl7nwdpG2yJSBY6pXnXFF9sdHoFAUI0uy1Pp6VU9b
/9uMzZo+BBaIfojwHCa91JcX3FwLly5sPmNAjgiTeYoFmeb7vmV9ZMjoda1B8k4e
8E0oVPgdDqCguBEP80NuosAONTib3fZ8ERmRw4HIwc9xjFDzyPpvyc25liyPKr57
UDoDbO/DwhrrKGZP11JZHUn4mIAO7pniZYj/IC47aXEEuZNn95zACGMYqfn8A9+K
mHIHwr4ifS+k8UmQ2ly+HX+NfKJLTIUBcQY+7w6C5CHrVBImVHzHTYLvKWGH3pmB
zn8cCTgwW7mJ8bzQezt1MozCB1CYKv/SelvxisIQqyxqYB9q41g9x3hkePDRlh1s
5ycvN0axEpSgxg10bLJdkhE+CfYkuANAyjQzAksFRa1ZlMQ5I+VVpXEECTVpLyLt
QQH87vtZS5xFaHUQnArXtZFu1WC0gZvMkNkJofv3GowNfanZb8iNtNFE8r1+GjL7
a9NhaD8She0z2xQ4eZm8+Mtpz9ap/F7RLa9YgnJth5bDwLlAe30lg+7WIZHilR09
UBHapoYlLB3B6RF51wWVneIlnTpMIJeP9vOGFBUqZ+W1j3O3uoLij1FUuwARAQAB
tDZDb3JlT1MgQnVpbGRib3QgKE9mZmljYWwgQnVpbGRzKSA8YnVpbGRib3RAY29y
ZW9zLmNvbT6JAjkEEwECACMFAlIqVhQCGwMHCwkIBwMCAQYVCAIJCgsEFgIDAQIe
AQIXgAAKCRBQ4IhVk9LctFkGD/46/I3S392oQQs81pUOMbPulCitA7/ehYPuVlgy
mv6+SEZOtafEJuI9uiTzlAVremZfalyL20RBtU10ANJfejp14rOpMadlRqz0DCvc
Wuuhhn9FEQE59Yk3LQ7DBLLbeJwUvEAtEEXq8xVXWh4OWgDiP5/3oALkJ4Lb3sFx
KwMy2JjkImr1XgMY7M2UVIomiSFD7v0H5Xjxaow/R6twttESyoO7TSI6eVyVgkWk
GjOSVK5MZOZlux7hW+uSbyUGPoYrfF6TKM9+UvBqxWzz9GBG44AjcViuOn9eH/kF
NoOAwzLcL0wjKs9lN1G4mhYALgzQx/2ZH5XO0IbfAx5Z0ZOgXk25gJajLTiqtOkM
E6u691Dx4c87kST2g7Cp3JMCC+cqG37xilbV4u03PD0izNBt/FLaTeddNpPJyttz
gYqeoSv2xCYC8AM9N73Yp1nT1G1rnCpe5Jct8Mwq7j8rQWIBArt3lt6mYFNjuNpg
om+rZstK8Ut1c8vOhSwz7Qza+3YaaNjLwaxe52RZ5svt6sCfIVO2sKHf3iO3aLzZ
5KrCLZ/8tJtVxlhxRh0TqJVqFvOneP7TxkZs9DkU5uq5lHc9FWObPfbW5lhrU36K
Pf5pn0XomaWqge+GCBCgF369ibWbUAyGPqYj5wr/jwmG6nedMiqcOwpeBljpDF1i
d9zMN4kCHAQQAQIABgUCUipXUQAKCRDAr7X91+bcxwvZD/0T4mVRyAp8+EhCta6f
Qnoiqc49oHhnKsoN7wDg45NRlQP84rH1knn4/nSpUzrB29bhY8OgAiXXMHVcS+Uk
hUsF0sHNlnunbY0GEuIziqnrjEisb1cdIGyfsWUPc/4+inzu31J1n3iQyxdOOkrA
ddd0iQxPtyEjwevAfptGUeAGvtFXP374XsEo2fbd+xHMdV1YkMImLGx0guOK8tgp
+ht7cyHkfsyymrCV/WGaTdGMwtoJOxNZyaS6l0ccneW4UhORda2wwD0mOHHk2EHG
dJuEN4SRSoXQ0zjXvFr/u3k7Qww11xU0V4c6ZPl0Rd/ziqbiDImlyODCx6KUlmJb
k4l77XhHezWD0l3ZwodCV0xSgkOKLkudtgHPOBgHnJSL0vy7Ts6UzM/QLX5GR7uj
do7P/v0FrhXB+bMKvB/fMVHsKQNqPepigfrJ4+dZki7qtpx0iXFOfazYUB4CeMHC
0gGIiBjQxKorzzcc5DVaVaGmmkYoBpxZeUsAD3YNFr6AVm3AGGZO4JahEOsul2FF
V6B0BiSwhg1SnZzBjkCcTCPURFm82aYsFuwWwqwizObZZNDC/DcFuuAuuEaarhO9
BGzShpdbM3Phb4tjKKEJ9Sps6FBC2Cf/1pmPyOWZToMXex5ZKB0XHGCI0DFlB4Tn
in95D/b2+nYGUehmneuAmgde87kCDQRSKlZGARAAuMYYnu48l3AvE8ZpTN6uXSt2
RrXnOr9oEah6hw1fn9KYKVJi0ZGJHzQOeAHHO/3BKYPFZNoUoNOU6VR/KAn7gon1
wkUwk9Tn0AXVIQ7wMFJNLvcinoTkLBT5tqcAz5MvAoI9sivAM0Rm2BgeujdHjRS+
UQKq/EZtpnodeQKE8+pwe3zdf6A9FZY2pnBs0PxKJ0NZ1rZeAW9w+2WdbyrkWxUv
jYWMSzTUkWK6533PVi7RcdRmWrDMNVR/X1PfqqAIzQkQ8oGcXtRpYjFL30Z/LhKe
c9Awfm57rkZk2EMduIB/Y5VYqnOsmKgUghXjOo6JOcanQZ4sHAyQrB2Yd6UgdAfz
qa7AWNIAljSGy6/CfJAoVIgl1revG7GCsRD5Dr/+BLyauwZ/YtTH9mGDtg6hy/So
zzDAM8+79Y8VMBUtj64GQBgg2+0MVZYNsZCN209X+EGpGUmAGEFQLGLHwFoNlwwL
1Uj+/5NTAhp2MQA/XRDTVx1nm8MZZXUOu6NTCUXtUmgTQuQEsKCosQzBuT/G+8Ia
R5jBVZ38/NJgLw+YcRPNVo2S2XSh7liw+Sl1sdjEW1nWQHotDAzd2MFG++KVbxwb
cXbDgJOB0+N0c362WQ7bzxpJZoaYGhNOVjVjNY8YkcOiDl0DqkCk45obz4hG2T08
x0OoXN7Oby0FclbUkVsAEQEAAYkERAQYAQIADwUCUipWRgIbAgUJAeEzgAIpCRBQ
4IhVk9LctMFdIAQZAQIABgUCUipWRgAKCRClQeyydOfjYdY6D/4+PmhaiyasTHqh
iui2DwDVdhwxdikQEl+KQQHtk7aqgbUAxgU1D4rbLxzXyhTbmql7D30nl+oZg0Be
yl67Xo6X/wHsP44651aTbwxVT9nzhOp6OEW5z/qxJaX1B9EBsYtjGO87N854xC6a
QEaGZPbNauRpcYEadkppSumBo5ujmRWc4S+H1VjQW4vGSCm9m4X7a7L7/063HJza
SYaHybbu/udWW8ymzuUf/UARH4141bGnZOtIa9vIGtFl2oWJ/ViyJew9vwdMqiI6
Y86ISQcGV/lL/iThNJBn+pots0CqdsoLvEZQGF3ZozWJVCKnnn/kC8NNyd7Wst9C
+p7ZzN3BTz+74Te5Vde3prQPFG4ClSzwJZ/U15boIMBPtNd7pRYum2padTK9oHp1
l5dI/cELluj5JXT58hs5RAn4xD5XRNb4ahtnc/wdqtle0Kr5O0qNGQ0+U6ALdy/f
IVpSXihfsiy45+nPgGpfnRVmjQvIWQelI25+cvqxX1dr827ksUj4h6af/Bm9JvPG
KKRhORXPe+OQM6y/ubJOpYPEq9fZxdClekjA9IXhojNA8C6QKy2Kan873XDE0H4K
Y2OMTqQ1/n1A6g3qWCWph/sPdEMCsfnybDPcdPZp3psTQ8uX/vGLz0AAORapVCbp
iFHbF3TduuvnKaBWXKjrr5tNY/njrU4zEADTzhgbtGW75HSGgN3wtsiieMdfbH/P
f7wcC2FlbaQmevXjWI5tyx2m3ejG9gqnjRSyN5DWPq0m5AfKCY+4Glfjf01l7wR2
5oOvwL9lTtyrFE68t3pylUtIdzDz3EG0LalVYpEDyTIygzrriRsdXC+Na1KXdr5E
GC0BZeG4QNS6XAsNS0/4SgT9ceA5DkgBCln58HRXabc25Tyfm2RiLQ70apWdEuoQ
TBoiWoMDeDmGLlquA5J2rBZh2XNThmpKU7PJ+2g3NQQubDeUjGEa6hvDwZ3vni6V
vVqsviCYJLcMHoHgJGtTTUoRO5Q6terCpRADMhQ014HYugZVBRdbbVGPo3YetrzU
/BuhvvROvb5dhWVi7zBUw2hUgQ0g0OpJB2TaJizXA+jIQ/x2HiO4QSUihp4JZJrL
5G4P8dv7c7/BOqdj19VXV974RAnqDNSpuAsnmObVDO3Oy0eKj1J1eSIp5ZOA9Q3d
bHinx13rh5nMVbn3FxIemTYEbUFUbqa0eB3GRFoDz4iBGR4NqwIboP317S27NLDY
J8L6KmXTyNh8/Cm2l7wKlkwi3ItBGoAT+j3cOG988+3slgM9vXMaQRRQv9O1aTs1
ZAai+Jq7AGjGh4ZkuG0cDZ2DuBy22XsUNboxQeHbQTsAPzQfvi+fQByUi6TzxiW0
BeiJ6tEeDHDzdLkCDQRUDREaARAA+Wuzp1ANTtPGooSq4W4fVUz+mlEpDV4fzK6n
HQ35qGVJgXEJVKxXy206jNHx3lro7BGcJtIXeRb+Wp1eGUghrG1+V/mKFxE4wulN
tFXoTOJ//AOYkPq9FG12VGeLZDckAR4zMhDwdcwsJ208hZzBSslJOWAuZTPoWple
+xie4B8jZiUcjf10XaWvBnlx4EPohhvtv5VEczZWNvGa/0VDe/FfI4qGknJM3+d0
kvXK/7yaFpdGwnY3nE/V4xbwx2tggqQRXoFmYbjogGHpTcdXkWbGEz5F7mLNwzZ/
voyTiZeukZP5I45CCLgiB+g2WTl8cm3gcxrnt/aZAJCAl/eclFeYQ/Xiq8sK1+U2
nDEYLWRygoZACULmLPbUEVmQBOw/HAufE98sb36MHcFss634h2ijIp9/wvnX9GOE
LgX4hgqkgM85QaMeaS3d2+jlMu8BdsMYxPkTumsEUShcFtAYgtrNrPSayHtV6I9I
41ISg8EIr9qEhH1xLGvSA+dfUvXqwa0cIBxhI3bXOa25vPHbT+SLtfQlvUvKySIb
c6fobw2Wf1ZtM8lgFL3f/dHbT6fsvK6Jd/8iVMAZkAYFbJcivjS9/ugXbMznz5Wv
g9O7hbQtXUvRjvh8+AzlASYidqSd6neW6o+i2xduUBlrbCfW6R0bPLX+7w9iqMaT
0wEQs3MAEQEAAYkERAQYAQIADwUCVA0RGgIbAgUJAeEzgAIpCRBQ4IhVk9LctMFd
IAQZAQIABgUCVA0RGgAKCRClqWY15Wdu/JYcD/95hNCztDFlwzYi2p9vfaMbnWcR
qzqavj21muB9vE/ybb9CQrcXd84y7oNq2zU7jOSAbT3aGloQDP9+N0YFkQoYGMRs
CPiTdnF7/mJCgAnXei6SO+H6PIw9qgC4wDV0UhCiNh+CrsICFFbK+O+Jbgj+CEN8
XtVhZz3UXbH/YWg/AV/XGWL1BT4bFilUdF6b2nJAtORYQFIUKwOtCAlI/ytBo34n
M6lrMdMhHv4MoBHP91+Y9+t4D/80ytOgH6lq0+fznY8Tty+ODh4WNkfXwXq+0TfZ
fJiZLvkoXGD+l/I+HE3gXn4MBwahQQZl8gzI9daEGqPF8KYX0xyyKGo+8yJG5/WG
lfdGeKmz8rGP/Ugyo6tt8DTSSqJv6otAF/AWV1Wu/DCniehtfHYrp2EHZUlpvGRl
7Ea9D9tv9BKYm6S4+2yD5KkPu4qp3r6glVbePPCLeZ4NLQCEIpKakIERfxk66JqZ
Tb5XI9HKKbnhKunOoGiL5SMXVsS67Sxt//Ta/3vSaLC3wnVwN5OeXNaa04Yx7jg/
wtMJ9Jz0EYFtVv2NLizEeGCI8iPJOyMWOy+twCIk5zmvwsLu5MKmg1tLI2mtCTYz
qo8uVIqETlojxIqAhRYtmeiYKf2fZs5um3+Sjv28v4nw3VfQgibTKc2uBjeqxxOe
XGw0ysKnS2VO72SK879+EADd3HoF9U80odCgN5T6aljhaNaruqmG4CvBdRyzp3EQ
9RP7jPOEhcM00etw572orviK9AqCk+zwvfzEFbt/uC7zOpO0BJ8fnMAZ0Zn/fF8s
88zR4zq6BBq9WD4RCmazw2G6IyGXHvVAWi8UxoNjNoJJosLyLauFdPPUeoye5PxE
g+fQew3behcCaebjZwUA+xZMj7dfwcNXlDa4VkCDHzTfU43znawBo9avB8hNwMeW
CZYINmym+LSKyQnz3sirTpYcjorxtov1fyml8413tDJoOvkotSX9o3QQgbBPsyQ7
nwLTscYc5eklGRH7iytXOPI+29EPpfRHX2DAnVyTeVSFPEr79tIsijy02ZBZTiKY
lBlJy/Cj2C5cGhVeQ6v4jnj1Nt3sjHkZlVfmipSYVfcBoID1/4r2zHl4OFlLCjvk
XUhbqhm9xWV8NdmItO3BBSlIEksFunykzz1HM6shvzw77sM5+TEtSsxoOxxys+9N
ItCl8L6yf84A5333pLaUWh5HON1J+jGGbKnUzXKBsDxGSvgDcFlyVloBRQShUkv3
FMem+FWqt7aA3/YFCPgyLp7818VhfM70bqIxLi0/BJHp6ltGN5EH+q7Ewz210VAB
ju5IO7bjgCqTFeR3YYUN87l8ofdARx3shApXS6TkVcwaTv5eqzdFO9fZeRqHj4L9
Pg==
=LY4G
-----END PGP PUBLIC KEY BLOCK-----
"

# gpg verify a file using the provided key
function gpg_verify() {
	sigfile=$1	#signature file (assumed to be suffixed form of file to verify)
	key=$2		#signing key
	keyid=$3	#signing key signature

	gpghome=$(mktemp -d)
	gpg --homedir="${gpghome}" --batch --quiet --import <<<"${key}"
	gpg --homedir="${gpghome}" --batch --trusted-key "${keyid}" --verify "${sigfile}"
	RES=$?

	rm -Rf "${gpghome}"

	return ${RES}
}

# maintain an gpg-verified url cache, assumes signature available @ $url.sig
function cache_url() {
	cache=$1
	url=$2
	key=$3
	keyid=$4
	sigfile="${cache}.sig"
	sigurl="${url}.sig"

	# ensure the cache directory exists
	mkdir -p $(dirname "${cache}")

	# verify the cached copy if it exists
	if ! gpg_verify "${sigfile}" "${key}" "${keyid}"; then

		# refresh the cache on failure, and verify it again
		curl --location --output "${cache}" "${url}"
		curl --location --output "${sigfile}" "${sigurl}"

		gpg_verify "${sigfile}" "${key}" "${keyid}" || return 1
	fi

	# file $cache exists and can be trusted
}

CACHED_IMG="${PWD}/cache/pxe.img"
WORK="mkroot"
USRFS="usr.squashfs"
ROOTDIR="${WORK}/rootfs"
BINDIR="${WORK}/bins"
USR="rootfs/usr"
FILELIST="filelist.txt"
OUTPUT=${OUTPUT:="../stage0/stage1_rootfs/bin.go"}

# cache pxe image
cache_url "${CACHED_IMG}" "${IMG_URL}" "${GPG_KEY}" "${GPG_LONG_ID}"

[ -e "${WORK}" ] && rm -Rf "${WORK}"

mkdir -p "${ROOTDIR}"

# derive $USRFS from $CACHED_IMG
pushd "${WORK}"
gzip -cd "${CACHED_IMG}" | cpio --extract "${USRFS}"

# extra stuff for stage1 which will come/go as things mature (reaper in bash for now)
EXTRAS="bin/bash
	lib64/libreadline.so
	lib64/libreadline.so.6
	lib64/libreadline.so.6.2
	lib64/libncurses.so
	lib64/libncurses.so.5
	lib64/libncurses.so.5.9
	lib64/libdl.so
	lib64/libdl.so.2
	lib64/libdl-2.17.so
	bin/sleep"

# systemd and dependencies
cat > "${FILELIST}" <<-EOF
	${EXTRAS}
	bin/journalctl
	bin/systemctl
	bin/systemd-analyze
	bin/systemd-ask-password
	bin/systemd-cat
	bin/systemd-cgls
	bin/systemd-cgtop
	bin/systemd-coredumpctl
	bin/coredumpctl
	bin/systemd-delta
	bin/systemd-detect-virt
	bin/systemd-inhibit
	bin/systemd-machine-id-setup
	bin/systemd-notify
	bin/systemd-nspawn
	bin/systemd-path
	bin/systemd-run
	bin/systemd-stdio-bridge
	bin/systemd-sysusers
	bin/systemd-tmpfiles
	bin/systemd-tty-ask-password-agent
	lib
	lib64/libattr.so
	lib64/libitm.so
	lib64/libitm.so.1
	lib64/libitm.so.1.0.0
	lib64/libblkid.so
	lib64/libblkid.so.1
	lib64/libblkid.so.1.1.0
	lib64/libuuid.so.1
	lib64/libuuid.so.1.3.0
	lib64/libuuid.so
	lib64/libstdc++.so
	lib64/libstdc++.so.6
	lib64/libstdc++.so.6.0.17
	lib64/libgcc_s.so
	lib64/libgcc_s.so.1
	lib64/librt-2.17.so
	lib64/libz.so.1
	lib64/libc.so
	lib64/libz.so.1.2.8
	lib64/libattr.so.1.1.0
	lib64/libpthread.so.0
	lib64/libz.so
	lib64/libseccomp.so.2.1.1
	lib64/libseccomp.so
	lib64/libpthread.so
	lib64/libcap.so.2.22
	lib64/libpthread-2.17.so
	lib64/libkmod.so.2
	lib64/ld-linux-x86-64.so.2
	lib64/ld-2.17.so
	lib64/librt.so.1
	lib64/libkmod.so
	lib64/libcap.so
	lib64/libc-2.17.so
	lib64/librt.so
	lib64/libseccomp.so.2
	lib64/libattr.so.1
	lib64/libkmod.so.2.2.5
	lib64/libcap.so.2
	lib64/libc.so.6
	lib64/systemd/systemd-backlight
	lib64/systemd/systemd-update-utmp
	lib64/systemd/systemd-vconsole-setup
	lib64/systemd/systemd-journal-remote
	lib64/systemd/systemd-modules-load
	lib64/systemd/systemd-resolved
	lib64/systemd/systemd-bus-proxyd
	lib64/systemd/systemd-ac-power
	lib64/systemd/systemd-bootchart
	lib64/systemd/systemd-initctl
	lib64/systemd/systemd-shutdown
	lib64/systemd/systemd-multi-seat-x
	lib64/systemd/systemd-rfkill
	lib64/systemd/systemd-networkd
	lib64/systemd/systemd-activate
	lib64/systemd/systemd-readahead
	lib64/systemd/systemd-hostnamed
	lib64/systemd/systemd-random-seed
	lib64/systemd/systemd-cgroups-agent
	lib64/systemd/systemd-udevd
	lib64/systemd/systemd-shutdownd
	lib64/systemd/systemd-logind
	lib64/systemd/systemd
	lib64/systemd/systemd-update-done
	lib64/systemd/systemd-machined
	lib64/systemd/systemd-user-sessions
	lib64/systemd/systemd-sysctl
	lib64/systemd/systemd-journald
	lib64/systemd/systemd-timedated
	lib64/systemd/systemd-networkd-wait-online
	lib64/systemd/systemd-localed
	lib64/systemd/systemd-cryptsetup
	lib64/systemd/user-generators
	lib64/systemd/systemd-remount-fs
	lib64/systemd/systemd-coredump
	lib64/systemd/systemd-timesyncd
	lib64/systemd/systemd-socket-proxyd
	lib64/systemd/system-shutdown
	lib64/systemd/systemd-binfmt
	lib64/systemd/systemd-fsck
	lib64/systemd/system-sleep
	lib64/systemd/systemd-sleep
	lib64/systemd/systemd-reply-password
	lib64/systemd/systemd-journal-gatewayd
	share/zoneinfo
	share/zoneinfo/US
	share/zoneinfo/US/Samoa
	share/zoneinfo/US/Alaska
	share/zoneinfo/US/Hawaii
	share/zoneinfo/US/Arizona
	share/zoneinfo/US/Indiana-Starke
	share/zoneinfo/US/Michigan
	share/zoneinfo/US/Eastern
	share/zoneinfo/US/Central
	share/zoneinfo/US/East-Indiana
	share/zoneinfo/US/Mountain
	share/zoneinfo/US/Pacific
	share/zoneinfo/US/Aleutian
	share/zoneinfo/US/Pacific-New
	share/zoneinfo/right
	share/zoneinfo/right/US
	share/zoneinfo/right/US/Samoa
	share/zoneinfo/right/US/Alaska
	share/zoneinfo/right/US/Hawaii
	share/zoneinfo/right/US/Arizona
	share/zoneinfo/right/US/Indiana-Starke
	share/zoneinfo/right/US/Michigan
	share/zoneinfo/right/US/Eastern
	share/zoneinfo/right/US/Central
	share/zoneinfo/right/US/East-Indiana
	share/zoneinfo/right/US/Mountain
	share/zoneinfo/right/US/Pacific
	share/zoneinfo/right/US/Aleutian
	share/zoneinfo/right/US/Pacific-New
	share/zoneinfo/right/Universal
	share/zoneinfo/right/Asia
	share/zoneinfo/right/Asia/Tbilisi
	share/zoneinfo/right/Asia/Jakarta
	share/zoneinfo/right/Asia/Riyadh89
	share/zoneinfo/right/Asia/Dubai
	share/zoneinfo/right/Asia/Colombo
	share/zoneinfo/right/Asia/Vientiane
	share/zoneinfo/right/Asia/Harbin
	share/zoneinfo/right/Asia/Taipei
	share/zoneinfo/right/Asia/Phnom_Penh
	share/zoneinfo/right/Asia/Ujung_Pandang
	share/zoneinfo/right/Asia/Makassar
	share/zoneinfo/right/Asia/Almaty
	share/zoneinfo/right/Asia/Baghdad
	share/zoneinfo/right/Asia/Aqtau
	share/zoneinfo/right/Asia/Irkutsk
	share/zoneinfo/right/Asia/Chungking
	share/zoneinfo/right/Asia/Bishkek
	share/zoneinfo/right/Asia/Shanghai
	share/zoneinfo/right/Asia/Saigon
	share/zoneinfo/right/Asia/Tashkent
	share/zoneinfo/right/Asia/Yerevan
	share/zoneinfo/right/Asia/Ashkhabad
	share/zoneinfo/right/Asia/Kamchatka
	share/zoneinfo/right/Asia/Baku
	share/zoneinfo/right/Asia/Tel_Aviv
	share/zoneinfo/right/Asia/Krasnoyarsk
	share/zoneinfo/right/Asia/Nicosia
	share/zoneinfo/right/Asia/Muscat
	share/zoneinfo/right/Asia/Qatar
	share/zoneinfo/right/Asia/Kathmandu
	share/zoneinfo/right/Asia/Hovd
	share/zoneinfo/right/Asia/Ho_Chi_Minh
	share/zoneinfo/right/Asia/Gaza
	share/zoneinfo/right/Asia/Singapore
	share/zoneinfo/right/Asia/Dacca
	share/zoneinfo/right/Asia/Anadyr
	share/zoneinfo/right/Asia/Riyadh
	share/zoneinfo/right/Asia/Beirut
	share/zoneinfo/right/Asia/Pyongyang
	share/zoneinfo/right/Asia/Thimbu
	share/zoneinfo/right/Asia/Kolkata
	share/zoneinfo/right/Asia/Urumqi
	share/zoneinfo/right/Asia/Jayapura
	share/zoneinfo/right/Asia/Riyadh88
	share/zoneinfo/right/Asia/Novosibirsk
	share/zoneinfo/right/Asia/Hong_Kong
	share/zoneinfo/right/Asia/Yekaterinburg
	share/zoneinfo/right/Asia/Dhaka
	share/zoneinfo/right/Asia/Oral
	share/zoneinfo/right/Asia/Manila
	share/zoneinfo/right/Asia/Tokyo
	share/zoneinfo/right/Asia/Riyadh87
	share/zoneinfo/right/Asia/Rangoon
	share/zoneinfo/right/Asia/Tehran
	share/zoneinfo/right/Asia/Ashgabat
	share/zoneinfo/right/Asia/Ust-Nera
	share/zoneinfo/right/Asia/Vladivostok
	share/zoneinfo/right/Asia/Yakutsk
	share/zoneinfo/right/Asia/Bahrain
	share/zoneinfo/right/Asia/Macao
	share/zoneinfo/right/Asia/Ulaanbaatar
	share/zoneinfo/right/Asia/Kuwait
	share/zoneinfo/right/Asia/Bangkok
	share/zoneinfo/right/Asia/Chongqing
	share/zoneinfo/right/Asia/Brunei
	share/zoneinfo/right/Asia/Aden
	share/zoneinfo/right/Asia/Kabul
	share/zoneinfo/right/Asia/Choibalsan
	share/zoneinfo/right/Asia/Istanbul
	share/zoneinfo/right/Asia/Samarkand
	share/zoneinfo/right/Asia/Karachi
	share/zoneinfo/right/Asia/Damascus
	share/zoneinfo/right/Asia/Novokuznetsk
	share/zoneinfo/right/Asia/Aqtobe
	share/zoneinfo/right/Asia/Jerusalem
	share/zoneinfo/right/Asia/Dili
	share/zoneinfo/right/Asia/Dushanbe
	share/zoneinfo/right/Asia/Amman
	share/zoneinfo/right/Asia/Ulan_Bator
	share/zoneinfo/right/Asia/Kashgar
	share/zoneinfo/right/Asia/Calcutta
	share/zoneinfo/right/Asia/Omsk
	share/zoneinfo/right/Asia/Kuching
	share/zoneinfo/right/Asia/Kuala_Lumpur
	share/zoneinfo/right/Asia/Pontianak
	share/zoneinfo/right/Asia/Katmandu
	share/zoneinfo/right/Asia/Seoul
	share/zoneinfo/right/Asia/Qyzylorda
	share/zoneinfo/right/Asia/Thimphu
	share/zoneinfo/right/Asia/Magadan
	share/zoneinfo/right/Asia/Macau
	share/zoneinfo/right/Asia/Khandyga
	share/zoneinfo/right/Asia/Sakhalin
	share/zoneinfo/right/Asia/Hebron
	share/zoneinfo/right/EST
	share/zoneinfo/right/Jamaica
	share/zoneinfo/right/NZ-CHAT
	share/zoneinfo/right/Iran
	share/zoneinfo/right/GB
	share/zoneinfo/right/Mideast
	share/zoneinfo/right/Mideast/Riyadh89
	share/zoneinfo/right/Mideast/Riyadh88
	share/zoneinfo/right/Mideast/Riyadh87
	share/zoneinfo/right/Europe
	share/zoneinfo/right/Europe/Sofia
	share/zoneinfo/right/Europe/Vienna
	share/zoneinfo/right/Europe/Moscow
	share/zoneinfo/right/Europe/Monaco
	share/zoneinfo/right/Europe/Warsaw
	share/zoneinfo/right/Europe/Lisbon
	share/zoneinfo/right/Europe/Chisinau
	share/zoneinfo/right/Europe/Prague
	share/zoneinfo/right/Europe/Belgrade
	share/zoneinfo/right/Europe/Vatican
	share/zoneinfo/right/Europe/Volgograd
	share/zoneinfo/right/Europe/Malta
	share/zoneinfo/right/Europe/Vaduz
	share/zoneinfo/right/Europe/Nicosia
	share/zoneinfo/right/Europe/Gibraltar
	share/zoneinfo/right/Europe/Paris
	share/zoneinfo/right/Europe/San_Marino
	share/zoneinfo/right/Europe/Brussels
	share/zoneinfo/right/Europe/Rome
	share/zoneinfo/right/Europe/Minsk
	share/zoneinfo/right/Europe/Isle_of_Man
	share/zoneinfo/right/Europe/Kaliningrad
	share/zoneinfo/right/Europe/Simferopol
	share/zoneinfo/right/Europe/Tirane
	share/zoneinfo/right/Europe/Sarajevo
	share/zoneinfo/right/Europe/Stockholm
	share/zoneinfo/right/Europe/Vilnius
	share/zoneinfo/right/Europe/Copenhagen
	share/zoneinfo/right/Europe/Skopje
	share/zoneinfo/right/Europe/Kiev
	share/zoneinfo/right/Europe/Amsterdam
	share/zoneinfo/right/Europe/Luxembourg
	share/zoneinfo/right/Europe/Bratislava
	share/zoneinfo/right/Europe/Riga
	share/zoneinfo/right/Europe/London
	share/zoneinfo/right/Europe/Athens
	share/zoneinfo/right/Europe/Samara
	share/zoneinfo/right/Europe/Mariehamn
	share/zoneinfo/right/Europe/Jersey
	share/zoneinfo/right/Europe/Uzhgorod
	share/zoneinfo/right/Europe/Istanbul
	share/zoneinfo/right/Europe/Belfast
	share/zoneinfo/right/Europe/Dublin
	share/zoneinfo/right/Europe/Zagreb
	share/zoneinfo/right/Europe/Zaporozhye
	share/zoneinfo/right/Europe/Helsinki
	share/zoneinfo/right/Europe/Bucharest
	share/zoneinfo/right/Europe/Andorra
	share/zoneinfo/right/Europe/Oslo
	share/zoneinfo/right/Europe/Ljubljana
	share/zoneinfo/right/Europe/Podgorica
	share/zoneinfo/right/Europe/Madrid
	share/zoneinfo/right/Europe/Berlin
	share/zoneinfo/right/Europe/Busingen
	share/zoneinfo/right/Europe/Budapest
	share/zoneinfo/right/Europe/Guernsey
	share/zoneinfo/right/Europe/Tallinn
	share/zoneinfo/right/Europe/Tiraspol
	share/zoneinfo/right/Europe/Zurich
	share/zoneinfo/right/Factory
	share/zoneinfo/right/ROC
	share/zoneinfo/right/UCT
	share/zoneinfo/right/GMT0
	share/zoneinfo/right/Atlantic
	share/zoneinfo/right/Atlantic/Faeroe
	share/zoneinfo/right/Atlantic/Cape_Verde
	share/zoneinfo/right/Atlantic/South_Georgia
	share/zoneinfo/right/Atlantic/Stanley
	share/zoneinfo/right/Atlantic/Bermuda
	share/zoneinfo/right/Atlantic/Faroe
	share/zoneinfo/right/Atlantic/Jan_Mayen
	share/zoneinfo/right/Atlantic/Reykjavik
	share/zoneinfo/right/Atlantic/St_Helena
	share/zoneinfo/right/Atlantic/Canary
	share/zoneinfo/right/Atlantic/Azores
	share/zoneinfo/right/Atlantic/Madeira
	share/zoneinfo/right/Zulu
	share/zoneinfo/right/EST5EDT
	share/zoneinfo/right/MST
	share/zoneinfo/right/Navajo
	share/zoneinfo/right/Hongkong
	share/zoneinfo/right/Egypt
	share/zoneinfo/right/PST8PDT
	share/zoneinfo/right/Chile
	share/zoneinfo/right/Chile/Continental
	share/zoneinfo/right/Chile/EasterIsland
	share/zoneinfo/right/Singapore
	share/zoneinfo/right/Indian
	share/zoneinfo/right/Indian/Mahe
	share/zoneinfo/right/Indian/Kerguelen
	share/zoneinfo/right/Indian/Mayotte
	share/zoneinfo/right/Indian/Cocos
	share/zoneinfo/right/Indian/Chagos
	share/zoneinfo/right/Indian/Antananarivo
	share/zoneinfo/right/Indian/Mauritius
	share/zoneinfo/right/Indian/Comoro
	share/zoneinfo/right/Indian/Christmas
	share/zoneinfo/right/Indian/Maldives
	share/zoneinfo/right/Indian/Reunion
	share/zoneinfo/right/Libya
	share/zoneinfo/right/Etc
	share/zoneinfo/right/Etc/Universal
	share/zoneinfo/right/Etc/GMT+2
	share/zoneinfo/right/Etc/GMT+12
	share/zoneinfo/right/Etc/UCT
	share/zoneinfo/right/Etc/GMT0
	share/zoneinfo/right/Etc/GMT-8
	share/zoneinfo/right/Etc/GMT+4
	share/zoneinfo/right/Etc/GMT+8
	share/zoneinfo/right/Etc/GMT-10
	share/zoneinfo/right/Etc/GMT+11
	share/zoneinfo/right/Etc/Zulu
	share/zoneinfo/right/Etc/GMT-12
	share/zoneinfo/right/Etc/GMT-3
	share/zoneinfo/right/Etc/GMT-7
	share/zoneinfo/right/Etc/GMT-11
	share/zoneinfo/right/Etc/GMT-4
	share/zoneinfo/right/Etc/GMT+5
	share/zoneinfo/right/Etc/GMT-2
	share/zoneinfo/right/Etc/GMT-13
	share/zoneinfo/right/Etc/GMT+9
	share/zoneinfo/right/Etc/GMT-14
	share/zoneinfo/right/Etc/Greenwich
	share/zoneinfo/right/Etc/GMT+0
	share/zoneinfo/right/Etc/GMT+10
	share/zoneinfo/right/Etc/UTC
	share/zoneinfo/right/Etc/GMT+7
	share/zoneinfo/right/Etc/GMT-6
	share/zoneinfo/right/Etc/GMT-0
	share/zoneinfo/right/Etc/GMT+3
	share/zoneinfo/right/Etc/GMT+6
	share/zoneinfo/right/Etc/GMT
	share/zoneinfo/right/Etc/GMT+1
	share/zoneinfo/right/Etc/GMT-5
	share/zoneinfo/right/Etc/GMT-1
	share/zoneinfo/right/Etc/GMT-9
	share/zoneinfo/right/W-SU
	share/zoneinfo/right/Africa
	share/zoneinfo/right/Africa/Asmera
	share/zoneinfo/right/Africa/Accra
	share/zoneinfo/right/Africa/Nouakchott
	share/zoneinfo/right/Africa/Abidjan
	share/zoneinfo/right/Africa/Banjul
	share/zoneinfo/right/Africa/Timbuktu
	share/zoneinfo/right/Africa/Maseru
	share/zoneinfo/right/Africa/Sao_Tome
	share/zoneinfo/right/Africa/Douala
	share/zoneinfo/right/Africa/Dakar
	share/zoneinfo/right/Africa/Porto-Novo
	share/zoneinfo/right/Africa/Juba
	share/zoneinfo/right/Africa/Mbabane
	share/zoneinfo/right/Africa/Johannesburg
	share/zoneinfo/right/Africa/Cairo
	share/zoneinfo/right/Africa/Gaborone
	share/zoneinfo/right/Africa/Tripoli
	share/zoneinfo/right/Africa/Algiers
	share/zoneinfo/right/Africa/Ndjamena
	share/zoneinfo/right/Africa/Windhoek
	share/zoneinfo/right/Africa/Conakry
	share/zoneinfo/right/Africa/Maputo
	share/zoneinfo/right/Africa/Djibouti
	share/zoneinfo/right/Africa/Dar_es_Salaam
	share/zoneinfo/right/Africa/Brazzaville
	share/zoneinfo/right/Africa/Ouagadougou
	share/zoneinfo/right/Africa/Harare
	share/zoneinfo/right/Africa/Ceuta
	share/zoneinfo/right/Africa/Casablanca
	share/zoneinfo/right/Africa/Bamako
	share/zoneinfo/right/Africa/Bissau
	share/zoneinfo/right/Africa/El_Aaiun
	share/zoneinfo/right/Africa/Bujumbura
	share/zoneinfo/right/Africa/Lagos
	share/zoneinfo/right/Africa/Luanda
	share/zoneinfo/right/Africa/Lome
	share/zoneinfo/right/Africa/Lusaka
	share/zoneinfo/right/Africa/Addis_Ababa
	share/zoneinfo/right/Africa/Tunis
	share/zoneinfo/right/Africa/Kigali
	share/zoneinfo/right/Africa/Khartoum
	share/zoneinfo/right/Africa/Malabo
	share/zoneinfo/right/Africa/Bangui
	share/zoneinfo/right/Africa/Mogadishu
	share/zoneinfo/right/Africa/Monrovia
	share/zoneinfo/right/Africa/Kinshasa
	share/zoneinfo/right/Africa/Blantyre
	share/zoneinfo/right/Africa/Kampala
	share/zoneinfo/right/Africa/Niamey
	share/zoneinfo/right/Africa/Nairobi
	share/zoneinfo/right/Africa/Freetown
	share/zoneinfo/right/Africa/Lubumbashi
	share/zoneinfo/right/Africa/Libreville
	share/zoneinfo/right/Africa/Asmara
	share/zoneinfo/right/MST7MDT
	share/zoneinfo/right/Greenwich
	share/zoneinfo/right/America
	share/zoneinfo/right/America/Mazatlan
	share/zoneinfo/right/America/Nassau
	share/zoneinfo/right/America/Swift_Current
	share/zoneinfo/right/America/Campo_Grande
	share/zoneinfo/right/America/Blanc-Sablon
	share/zoneinfo/right/America/Santarem
	share/zoneinfo/right/America/Grenada
	share/zoneinfo/right/America/Argentina
	share/zoneinfo/right/America/Argentina/Rio_Gallegos
	share/zoneinfo/right/America/Argentina/Tucuman
	share/zoneinfo/right/America/Argentina/Buenos_Aires
	share/zoneinfo/right/America/Argentina/Catamarca
	share/zoneinfo/right/America/Argentina/Mendoza
	share/zoneinfo/right/America/Argentina/San_Luis
	share/zoneinfo/right/America/Argentina/Salta
	share/zoneinfo/right/America/Argentina/ComodRivadavia
	share/zoneinfo/right/America/Argentina/Cordoba
	share/zoneinfo/right/America/Argentina/Ushuaia
	share/zoneinfo/right/America/Argentina/Jujuy
	share/zoneinfo/right/America/Argentina/La_Rioja
	share/zoneinfo/right/America/Argentina/San_Juan
	share/zoneinfo/right/America/Rio_Branco
	share/zoneinfo/right/America/Atka
	share/zoneinfo/right/America/Rosario
	share/zoneinfo/right/America/Anguilla
	share/zoneinfo/right/America/Anchorage
	share/zoneinfo/right/America/Metlakatla
	share/zoneinfo/right/America/Jamaica
	share/zoneinfo/right/America/St_Kitts
	share/zoneinfo/right/America/Cayenne
	share/zoneinfo/right/America/Recife
	share/zoneinfo/right/America/St_Vincent
	share/zoneinfo/right/America/El_Salvador
	share/zoneinfo/right/America/Kralendijk
	share/zoneinfo/right/America/Chihuahua
	share/zoneinfo/right/America/Araguaina
	share/zoneinfo/right/America/Curacao
	share/zoneinfo/right/America/Porto_Acre
	share/zoneinfo/right/America/Boa_Vista
	share/zoneinfo/right/America/Manaus
	share/zoneinfo/right/America/Ojinaga
	share/zoneinfo/right/America/Managua
	share/zoneinfo/right/America/Chicago
	share/zoneinfo/right/America/Sao_Paulo
	share/zoneinfo/right/America/Asuncion
	share/zoneinfo/right/America/Guadeloupe
	share/zoneinfo/right/America/Martinique
	share/zoneinfo/right/America/Boise
	share/zoneinfo/right/America/Godthab
	share/zoneinfo/right/America/Danmarkshavn
	share/zoneinfo/right/America/Rankin_Inlet
	share/zoneinfo/right/America/Guayaquil
	share/zoneinfo/right/America/Iqaluit
	share/zoneinfo/right/America/Barbados
	share/zoneinfo/right/America/Dominica
	share/zoneinfo/right/America/Indianapolis
	share/zoneinfo/right/America/St_Johns
	share/zoneinfo/right/America/Buenos_Aires
	share/zoneinfo/right/America/Halifax
	share/zoneinfo/right/America/Catamarca
	share/zoneinfo/right/America/Ensenada
	share/zoneinfo/right/America/Vancouver
	share/zoneinfo/right/America/Atikokan
	share/zoneinfo/right/America/Regina
	share/zoneinfo/right/America/Grand_Turk
	share/zoneinfo/right/America/St_Barthelemy
	share/zoneinfo/right/America/Nome
	share/zoneinfo/right/America/Montserrat
	share/zoneinfo/right/America/Port-au-Prince
	share/zoneinfo/right/America/Winnipeg
	share/zoneinfo/right/America/Virgin
	share/zoneinfo/right/America/Fort_Wayne
	share/zoneinfo/right/America/Tegucigalpa
	share/zoneinfo/right/America/Mendoza
	share/zoneinfo/right/America/Paramaribo
	share/zoneinfo/right/America/Belem
	share/zoneinfo/right/America/Louisville
	share/zoneinfo/right/America/Merida
	share/zoneinfo/right/America/Creston
	share/zoneinfo/right/America/La_Paz
	share/zoneinfo/right/America/Coral_Harbour
	share/zoneinfo/right/America/New_York
	share/zoneinfo/right/America/Port_of_Spain
	share/zoneinfo/right/America/St_Thomas
	share/zoneinfo/right/America/Puerto_Rico
	share/zoneinfo/right/America/Matamoros
	share/zoneinfo/right/America/Santo_Domingo
	share/zoneinfo/right/America/Edmonton
	share/zoneinfo/right/America/Knox_IN
	share/zoneinfo/right/America/Antigua
	share/zoneinfo/right/America/Tortola
	share/zoneinfo/right/America/Dawson_Creek
	share/zoneinfo/right/America/Indiana
	share/zoneinfo/right/America/Indiana/Winamac
	share/zoneinfo/right/America/Indiana/Indianapolis
	share/zoneinfo/right/America/Indiana/Petersburg
	share/zoneinfo/right/America/Indiana/Knox
	share/zoneinfo/right/America/Indiana/Vevay
	share/zoneinfo/right/America/Indiana/Marengo
	share/zoneinfo/right/America/Indiana/Vincennes
	share/zoneinfo/right/America/Indiana/Tell_City
	share/zoneinfo/right/America/Santa_Isabel
	share/zoneinfo/right/America/Pangnirtung
	share/zoneinfo/right/America/Los_Angeles
	share/zoneinfo/right/America/Cancun
	share/zoneinfo/right/America/Toronto
	share/zoneinfo/right/America/Guatemala
	share/zoneinfo/right/America/Cayman
	share/zoneinfo/right/America/Miquelon
	share/zoneinfo/right/America/Goose_Bay
	share/zoneinfo/right/America/Eirunepe
	share/zoneinfo/right/America/Resolute
	share/zoneinfo/right/America/Cordoba
	share/zoneinfo/right/America/Aruba
	share/zoneinfo/right/America/Santiago
	share/zoneinfo/right/America/Lower_Princes
	share/zoneinfo/right/America/Monterrey
	share/zoneinfo/right/America/Costa_Rica
	share/zoneinfo/right/America/Sitka
	share/zoneinfo/right/America/St_Lucia
	share/zoneinfo/right/America/Nipigon
	share/zoneinfo/right/America/Panama
	share/zoneinfo/right/America/Belize
	share/zoneinfo/right/America/Marigot
	share/zoneinfo/right/America/Porto_Velho
	share/zoneinfo/right/America/Bahia
	share/zoneinfo/right/America/Rainy_River
	share/zoneinfo/right/America/Denver
	share/zoneinfo/right/America/Kentucky
	share/zoneinfo/right/America/Kentucky/Louisville
	share/zoneinfo/right/America/Kentucky/Monticello
	share/zoneinfo/right/America/Moncton
	share/zoneinfo/right/America/Thunder_Bay
	share/zoneinfo/right/America/Yakutat
	share/zoneinfo/right/America/Cuiaba
	share/zoneinfo/right/America/Caracas
	share/zoneinfo/right/America/Glace_Bay
	share/zoneinfo/right/America/Guyana
	share/zoneinfo/right/America/Cambridge_Bay
	share/zoneinfo/right/America/Fortaleza
	share/zoneinfo/right/America/Montreal
	share/zoneinfo/right/America/Havana
	share/zoneinfo/right/America/Menominee
	share/zoneinfo/right/America/Shiprock
	share/zoneinfo/right/America/Maceio
	share/zoneinfo/right/America/Bogota
	share/zoneinfo/right/America/Jujuy
	share/zoneinfo/right/America/Bahia_Banderas
	share/zoneinfo/right/America/Whitehorse
	share/zoneinfo/right/America/Dawson
	share/zoneinfo/right/America/Juneau
	share/zoneinfo/right/America/Phoenix
	share/zoneinfo/right/America/Detroit
	share/zoneinfo/right/America/Inuvik
	share/zoneinfo/right/America/Adak
	share/zoneinfo/right/America/Hermosillo
	share/zoneinfo/right/America/Thule
	share/zoneinfo/right/America/Noronha
	share/zoneinfo/right/America/North_Dakota
	share/zoneinfo/right/America/North_Dakota/Center
	share/zoneinfo/right/America/North_Dakota/New_Salem
	share/zoneinfo/right/America/North_Dakota/Beulah
	share/zoneinfo/right/America/Lima
	share/zoneinfo/right/America/Montevideo
	share/zoneinfo/right/America/Scoresbysund
	share/zoneinfo/right/America/Tijuana
	share/zoneinfo/right/America/Yellowknife
	share/zoneinfo/right/America/Mexico_City
	share/zoneinfo/right/NZ
	share/zoneinfo/right/PRC
	share/zoneinfo/right/WET
	share/zoneinfo/right/GMT+0
	share/zoneinfo/right/Pacific
	share/zoneinfo/right/Pacific/Samoa
	share/zoneinfo/right/Pacific/Johnston
	share/zoneinfo/right/Pacific/Guam
	share/zoneinfo/right/Pacific/Guadalcanal
	share/zoneinfo/right/Pacific/Majuro
	share/zoneinfo/right/Pacific/Truk
	share/zoneinfo/right/Pacific/Auckland
	share/zoneinfo/right/Pacific/Fakaofo
	share/zoneinfo/right/Pacific/Honolulu
	share/zoneinfo/right/Pacific/Nauru
	share/zoneinfo/right/Pacific/Kiritimati
	share/zoneinfo/right/Pacific/Funafuti
	share/zoneinfo/right/Pacific/Tahiti
	share/zoneinfo/right/Pacific/Chatham
	share/zoneinfo/right/Pacific/Norfolk
	share/zoneinfo/right/Pacific/Enderbury
	share/zoneinfo/right/Pacific/Kosrae
	share/zoneinfo/right/Pacific/Apia
	share/zoneinfo/right/Pacific/Saipan
	share/zoneinfo/right/Pacific/Chuuk
	share/zoneinfo/right/Pacific/Pitcairn
	share/zoneinfo/right/Pacific/Ponape
	share/zoneinfo/right/Pacific/Yap
	share/zoneinfo/right/Pacific/Wallis
	share/zoneinfo/right/Pacific/Galapagos
	share/zoneinfo/right/Pacific/Pohnpei
	share/zoneinfo/right/Pacific/Tongatapu
	share/zoneinfo/right/Pacific/Easter
	share/zoneinfo/right/Pacific/Wake
	share/zoneinfo/right/Pacific/Pago_Pago
	share/zoneinfo/right/Pacific/Marquesas
	share/zoneinfo/right/Pacific/Noumea
	share/zoneinfo/right/Pacific/Tarawa
	share/zoneinfo/right/Pacific/Gambier
	share/zoneinfo/right/Pacific/Niue
	share/zoneinfo/right/Pacific/Palau
	share/zoneinfo/right/Pacific/Kwajalein
	share/zoneinfo/right/Pacific/Midway
	share/zoneinfo/right/Pacific/Rarotonga
	share/zoneinfo/right/Pacific/Fiji
	share/zoneinfo/right/Pacific/Port_Moresby
	share/zoneinfo/right/Pacific/Efate
	share/zoneinfo/right/Japan
	share/zoneinfo/right/Israel
	share/zoneinfo/right/UTC
	share/zoneinfo/right/Brazil
	share/zoneinfo/right/Brazil/Acre
	share/zoneinfo/right/Brazil/DeNoronha
	share/zoneinfo/right/Brazil/East
	share/zoneinfo/right/Brazil/West
	share/zoneinfo/right/Antarctica
	share/zoneinfo/right/Antarctica/Macquarie
	share/zoneinfo/right/Antarctica/Palmer
	share/zoneinfo/right/Antarctica/DumontDUrville
	share/zoneinfo/right/Antarctica/South_Pole
	share/zoneinfo/right/Antarctica/Vostok
	share/zoneinfo/right/Antarctica/McMurdo
	share/zoneinfo/right/Antarctica/Casey
	share/zoneinfo/right/Antarctica/Mawson
	share/zoneinfo/right/Antarctica/Davis
	share/zoneinfo/right/Antarctica/Syowa
	share/zoneinfo/right/Antarctica/Rothera
	share/zoneinfo/right/HST
	share/zoneinfo/right/Poland
	share/zoneinfo/right/Canada
	share/zoneinfo/right/Canada/Atlantic
	share/zoneinfo/right/Canada/Eastern
	share/zoneinfo/right/Canada/Central
	share/zoneinfo/right/Canada/Mountain
	share/zoneinfo/right/Canada/Yukon
	share/zoneinfo/right/Canada/Pacific
	share/zoneinfo/right/Canada/Saskatchewan
	share/zoneinfo/right/Canada/East-Saskatchewan
	share/zoneinfo/right/Canada/Newfoundland
	share/zoneinfo/right/Mexico
	share/zoneinfo/right/Mexico/General
	share/zoneinfo/right/Mexico/BajaSur
	share/zoneinfo/right/Mexico/BajaNorte
	share/zoneinfo/right/EET
	share/zoneinfo/right/MET
	share/zoneinfo/right/Turkey
	share/zoneinfo/right/Australia
	share/zoneinfo/right/Australia/Eucla
	share/zoneinfo/right/Australia/Sydney
	share/zoneinfo/right/Australia/Tasmania
	share/zoneinfo/right/Australia/Queensland
	share/zoneinfo/right/Australia/Hobart
	share/zoneinfo/right/Australia/Darwin
	share/zoneinfo/right/Australia/Lindeman
	share/zoneinfo/right/Australia/Adelaide
	share/zoneinfo/right/Australia/Canberra
	share/zoneinfo/right/Australia/LHI
	share/zoneinfo/right/Australia/Perth
	share/zoneinfo/right/Australia/North
	share/zoneinfo/right/Australia/ACT
	share/zoneinfo/right/Australia/Melbourne
	share/zoneinfo/right/Australia/Currie
	share/zoneinfo/right/Australia/Victoria
	share/zoneinfo/right/Australia/Lord_Howe
	share/zoneinfo/right/Australia/West
	share/zoneinfo/right/Australia/Broken_Hill
	share/zoneinfo/right/Australia/Brisbane
	share/zoneinfo/right/Australia/Yancowinna
	share/zoneinfo/right/Australia/South
	share/zoneinfo/right/Australia/NSW
	share/zoneinfo/right/GMT-0
	share/zoneinfo/right/GMT
	share/zoneinfo/right/Eire
	share/zoneinfo/right/Cuba
	share/zoneinfo/right/Portugal
	share/zoneinfo/right/Iceland
	share/zoneinfo/right/Kwajalein
	share/zoneinfo/right/ROK
	share/zoneinfo/right/GB-Eire
	share/zoneinfo/right/Arctic
	share/zoneinfo/right/Arctic/Longyearbyen
	share/zoneinfo/right/CET
	share/zoneinfo/right/CST6CDT
	share/zoneinfo/Universal
	share/zoneinfo/Asia
	share/zoneinfo/Asia/Tbilisi
	share/zoneinfo/Asia/Jakarta
	share/zoneinfo/Asia/Riyadh89
	share/zoneinfo/Asia/Dubai
	share/zoneinfo/Asia/Colombo
	share/zoneinfo/Asia/Vientiane
	share/zoneinfo/Asia/Harbin
	share/zoneinfo/Asia/Taipei
	share/zoneinfo/Asia/Phnom_Penh
	share/zoneinfo/Asia/Ujung_Pandang
	share/zoneinfo/Asia/Makassar
	share/zoneinfo/Asia/Almaty
	share/zoneinfo/Asia/Baghdad
	share/zoneinfo/Asia/Aqtau
	share/zoneinfo/Asia/Irkutsk
	share/zoneinfo/Asia/Chungking
	share/zoneinfo/Asia/Bishkek
	share/zoneinfo/Asia/Shanghai
	share/zoneinfo/Asia/Saigon
	share/zoneinfo/Asia/Tashkent
	share/zoneinfo/Asia/Yerevan
	share/zoneinfo/Asia/Ashkhabad
	share/zoneinfo/Asia/Kamchatka
	share/zoneinfo/Asia/Baku
	share/zoneinfo/Asia/Tel_Aviv
	share/zoneinfo/Asia/Krasnoyarsk
	share/zoneinfo/Asia/Nicosia
	share/zoneinfo/Asia/Muscat
	share/zoneinfo/Asia/Qatar
	share/zoneinfo/Asia/Kathmandu
	share/zoneinfo/Asia/Hovd
	share/zoneinfo/Asia/Ho_Chi_Minh
	share/zoneinfo/Asia/Gaza
	share/zoneinfo/Asia/Singapore
	share/zoneinfo/Asia/Dacca
	share/zoneinfo/Asia/Anadyr
	share/zoneinfo/Asia/Riyadh
	share/zoneinfo/Asia/Beirut
	share/zoneinfo/Asia/Pyongyang
	share/zoneinfo/Asia/Thimbu
	share/zoneinfo/Asia/Kolkata
	share/zoneinfo/Asia/Urumqi
	share/zoneinfo/Asia/Jayapura
	share/zoneinfo/Asia/Riyadh88
	share/zoneinfo/Asia/Novosibirsk
	share/zoneinfo/Asia/Hong_Kong
	share/zoneinfo/Asia/Yekaterinburg
	share/zoneinfo/Asia/Dhaka
	share/zoneinfo/Asia/Oral
	share/zoneinfo/Asia/Manila
	share/zoneinfo/Asia/Tokyo
	share/zoneinfo/Asia/Riyadh87
	share/zoneinfo/Asia/Rangoon
	share/zoneinfo/Asia/Tehran
	share/zoneinfo/Asia/Ashgabat
	share/zoneinfo/Asia/Ust-Nera
	share/zoneinfo/Asia/Vladivostok
	share/zoneinfo/Asia/Yakutsk
	share/zoneinfo/Asia/Bahrain
	share/zoneinfo/Asia/Macao
	share/zoneinfo/Asia/Ulaanbaatar
	share/zoneinfo/Asia/Kuwait
	share/zoneinfo/Asia/Bangkok
	share/zoneinfo/Asia/Chongqing
	share/zoneinfo/Asia/Brunei
	share/zoneinfo/Asia/Aden
	share/zoneinfo/Asia/Kabul
	share/zoneinfo/Asia/Choibalsan
	share/zoneinfo/Asia/Istanbul
	share/zoneinfo/Asia/Samarkand
	share/zoneinfo/Asia/Karachi
	share/zoneinfo/Asia/Damascus
	share/zoneinfo/Asia/Novokuznetsk
	share/zoneinfo/Asia/Aqtobe
	share/zoneinfo/Asia/Jerusalem
	share/zoneinfo/Asia/Dili
	share/zoneinfo/Asia/Dushanbe
	share/zoneinfo/Asia/Amman
	share/zoneinfo/Asia/Ulan_Bator
	share/zoneinfo/Asia/Kashgar
	share/zoneinfo/Asia/Calcutta
	share/zoneinfo/Asia/Omsk
	share/zoneinfo/Asia/Kuching
	share/zoneinfo/Asia/Kuala_Lumpur
	share/zoneinfo/Asia/Pontianak
	share/zoneinfo/Asia/Katmandu
	share/zoneinfo/Asia/Seoul
	share/zoneinfo/Asia/Qyzylorda
	share/zoneinfo/Asia/Thimphu
	share/zoneinfo/Asia/Magadan
	share/zoneinfo/Asia/Macau
	share/zoneinfo/Asia/Khandyga
	share/zoneinfo/Asia/Sakhalin
	share/zoneinfo/Asia/Hebron
	share/zoneinfo/EST
	share/zoneinfo/Jamaica
	share/zoneinfo/NZ-CHAT
	share/zoneinfo/iso3166.tab
	share/zoneinfo/Iran
	share/zoneinfo/GB
	share/zoneinfo/Mideast
	share/zoneinfo/Mideast/Riyadh89
	share/zoneinfo/Mideast/Riyadh88
	share/zoneinfo/Mideast/Riyadh87
	share/zoneinfo/Europe
	share/zoneinfo/Europe/Sofia
	share/zoneinfo/Europe/Vienna
	share/zoneinfo/Europe/Moscow
	share/zoneinfo/Europe/Monaco
	share/zoneinfo/Europe/Warsaw
	share/zoneinfo/Europe/Lisbon
	share/zoneinfo/Europe/Chisinau
	share/zoneinfo/Europe/Prague
	share/zoneinfo/Europe/Belgrade
	share/zoneinfo/Europe/Vatican
	share/zoneinfo/Europe/Volgograd
	share/zoneinfo/Europe/Malta
	share/zoneinfo/Europe/Vaduz
	share/zoneinfo/Europe/Nicosia
	share/zoneinfo/Europe/Gibraltar
	share/zoneinfo/Europe/Paris
	share/zoneinfo/Europe/San_Marino
	share/zoneinfo/Europe/Brussels
	share/zoneinfo/Europe/Rome
	share/zoneinfo/Europe/Minsk
	share/zoneinfo/Europe/Isle_of_Man
	share/zoneinfo/Europe/Kaliningrad
	share/zoneinfo/Europe/Simferopol
	share/zoneinfo/Europe/Tirane
	share/zoneinfo/Europe/Sarajevo
	share/zoneinfo/Europe/Stockholm
	share/zoneinfo/Europe/Vilnius
	share/zoneinfo/Europe/Copenhagen
	share/zoneinfo/Europe/Skopje
	share/zoneinfo/Europe/Kiev
	share/zoneinfo/Europe/Amsterdam
	share/zoneinfo/Europe/Luxembourg
	share/zoneinfo/Europe/Bratislava
	share/zoneinfo/Europe/Riga
	share/zoneinfo/Europe/London
	share/zoneinfo/Europe/Athens
	share/zoneinfo/Europe/Samara
	share/zoneinfo/Europe/Mariehamn
	share/zoneinfo/Europe/Jersey
	share/zoneinfo/Europe/Uzhgorod
	share/zoneinfo/Europe/Istanbul
	share/zoneinfo/Europe/Belfast
	share/zoneinfo/Europe/Dublin
	share/zoneinfo/Europe/Zagreb
	share/zoneinfo/Europe/Zaporozhye
	share/zoneinfo/Europe/Helsinki
	share/zoneinfo/Europe/Bucharest
	share/zoneinfo/Europe/Andorra
	share/zoneinfo/Europe/Oslo
	share/zoneinfo/Europe/Ljubljana
	share/zoneinfo/Europe/Podgorica
	share/zoneinfo/Europe/Madrid
	share/zoneinfo/Europe/Berlin
	share/zoneinfo/Europe/Busingen
	share/zoneinfo/Europe/Budapest
	share/zoneinfo/Europe/Guernsey
	share/zoneinfo/Europe/Tallinn
	share/zoneinfo/Europe/Tiraspol
	share/zoneinfo/Europe/Zurich
	share/zoneinfo/Factory
	share/zoneinfo/ROC
	share/zoneinfo/UCT
	share/zoneinfo/GMT0
	share/zoneinfo/Atlantic
	share/zoneinfo/Atlantic/Faeroe
	share/zoneinfo/Atlantic/Cape_Verde
	share/zoneinfo/Atlantic/South_Georgia
	share/zoneinfo/Atlantic/Stanley
	share/zoneinfo/Atlantic/Bermuda
	share/zoneinfo/Atlantic/Faroe
	share/zoneinfo/Atlantic/Jan_Mayen
	share/zoneinfo/Atlantic/Reykjavik
	share/zoneinfo/Atlantic/St_Helena
	share/zoneinfo/Atlantic/Canary
	share/zoneinfo/Atlantic/Azores
	share/zoneinfo/Atlantic/Madeira
	share/zoneinfo/Zulu
	share/zoneinfo/EST5EDT
	share/zoneinfo/MST
	share/zoneinfo/Navajo
	share/zoneinfo/Hongkong
	share/zoneinfo/Egypt
	share/zoneinfo/PST8PDT
	share/zoneinfo/Chile
	share/zoneinfo/Chile/Continental
	share/zoneinfo/Chile/EasterIsland
	share/zoneinfo/Singapore
	share/zoneinfo/Indian
	share/zoneinfo/Indian/Mahe
	share/zoneinfo/Indian/Kerguelen
	share/zoneinfo/Indian/Mayotte
	share/zoneinfo/Indian/Cocos
	share/zoneinfo/Indian/Chagos
	share/zoneinfo/Indian/Antananarivo
	share/zoneinfo/Indian/Mauritius
	share/zoneinfo/Indian/Comoro
	share/zoneinfo/Indian/Christmas
	share/zoneinfo/Indian/Maldives
	share/zoneinfo/Indian/Reunion
	share/zoneinfo/Libya
	share/zoneinfo/Etc
	share/zoneinfo/Etc/Universal
	share/zoneinfo/Etc/GMT+2
	share/zoneinfo/Etc/GMT+12
	share/zoneinfo/Etc/UCT
	share/zoneinfo/Etc/GMT0
	share/zoneinfo/Etc/GMT-8
	share/zoneinfo/Etc/GMT+4
	share/zoneinfo/Etc/GMT+8
	share/zoneinfo/Etc/GMT-10
	share/zoneinfo/Etc/GMT+11
	share/zoneinfo/Etc/Zulu
	share/zoneinfo/Etc/GMT-12
	share/zoneinfo/Etc/GMT-3
	share/zoneinfo/Etc/GMT-7
	share/zoneinfo/Etc/GMT-11
	share/zoneinfo/Etc/GMT-4
	share/zoneinfo/Etc/GMT+5
	share/zoneinfo/Etc/GMT-2
	share/zoneinfo/Etc/GMT-13
	share/zoneinfo/Etc/GMT+9
	share/zoneinfo/Etc/GMT-14
	share/zoneinfo/Etc/Greenwich
	share/zoneinfo/Etc/GMT+0
	share/zoneinfo/Etc/GMT+10
	share/zoneinfo/Etc/UTC
	share/zoneinfo/Etc/GMT+7
	share/zoneinfo/Etc/GMT-6
	share/zoneinfo/Etc/GMT-0
	share/zoneinfo/Etc/GMT+3
	share/zoneinfo/Etc/GMT+6
	share/zoneinfo/Etc/GMT
	share/zoneinfo/Etc/GMT+1
	share/zoneinfo/Etc/GMT-5
	share/zoneinfo/Etc/GMT-1
	share/zoneinfo/Etc/GMT-9
	share/zoneinfo/W-SU
	share/zoneinfo/Africa
	share/zoneinfo/Africa/Asmera
	share/zoneinfo/Africa/Accra
	share/zoneinfo/Africa/Nouakchott
	share/zoneinfo/Africa/Abidjan
	share/zoneinfo/Africa/Banjul
	share/zoneinfo/Africa/Timbuktu
	share/zoneinfo/Africa/Maseru
	share/zoneinfo/Africa/Sao_Tome
	share/zoneinfo/Africa/Douala
	share/zoneinfo/Africa/Dakar
	share/zoneinfo/Africa/Porto-Novo
	share/zoneinfo/Africa/Juba
	share/zoneinfo/Africa/Mbabane
	share/zoneinfo/Africa/Johannesburg
	share/zoneinfo/Africa/Cairo
	share/zoneinfo/Africa/Gaborone
	share/zoneinfo/Africa/Tripoli
	share/zoneinfo/Africa/Algiers
	share/zoneinfo/Africa/Ndjamena
	share/zoneinfo/Africa/Windhoek
	share/zoneinfo/Africa/Conakry
	share/zoneinfo/Africa/Maputo
	share/zoneinfo/Africa/Djibouti
	share/zoneinfo/Africa/Dar_es_Salaam
	share/zoneinfo/Africa/Brazzaville
	share/zoneinfo/Africa/Ouagadougou
	share/zoneinfo/Africa/Harare
	share/zoneinfo/Africa/Ceuta
	share/zoneinfo/Africa/Casablanca
	share/zoneinfo/Africa/Bamako
	share/zoneinfo/Africa/Bissau
	share/zoneinfo/Africa/El_Aaiun
	share/zoneinfo/Africa/Bujumbura
	share/zoneinfo/Africa/Lagos
	share/zoneinfo/Africa/Luanda
	share/zoneinfo/Africa/Lome
	share/zoneinfo/Africa/Lusaka
	share/zoneinfo/Africa/Addis_Ababa
	share/zoneinfo/Africa/Tunis
	share/zoneinfo/Africa/Kigali
	share/zoneinfo/Africa/Khartoum
	share/zoneinfo/Africa/Malabo
	share/zoneinfo/Africa/Bangui
	share/zoneinfo/Africa/Mogadishu
	share/zoneinfo/Africa/Monrovia
	share/zoneinfo/Africa/Kinshasa
	share/zoneinfo/Africa/Blantyre
	share/zoneinfo/Africa/Kampala
	share/zoneinfo/Africa/Niamey
	share/zoneinfo/Africa/Nairobi
	share/zoneinfo/Africa/Freetown
	share/zoneinfo/Africa/Lubumbashi
	share/zoneinfo/Africa/Libreville
	share/zoneinfo/Africa/Asmara
	share/zoneinfo/MST7MDT
	share/zoneinfo/Greenwich
	share/zoneinfo/America
	share/zoneinfo/America/Mazatlan
	share/zoneinfo/America/Nassau
	share/zoneinfo/America/Swift_Current
	share/zoneinfo/America/Campo_Grande
	share/zoneinfo/America/Blanc-Sablon
	share/zoneinfo/America/Santarem
	share/zoneinfo/America/Grenada
	share/zoneinfo/America/Argentina
	share/zoneinfo/America/Argentina/Rio_Gallegos
	share/zoneinfo/America/Argentina/Tucuman
	share/zoneinfo/America/Argentina/Buenos_Aires
	share/zoneinfo/America/Argentina/Catamarca
	share/zoneinfo/America/Argentina/Mendoza
	share/zoneinfo/America/Argentina/San_Luis
	share/zoneinfo/America/Argentina/Salta
	share/zoneinfo/America/Argentina/ComodRivadavia
	share/zoneinfo/America/Argentina/Cordoba
	share/zoneinfo/America/Argentina/Ushuaia
	share/zoneinfo/America/Argentina/Jujuy
	share/zoneinfo/America/Argentina/La_Rioja
	share/zoneinfo/America/Argentina/San_Juan
	share/zoneinfo/America/Rio_Branco
	share/zoneinfo/America/Atka
	share/zoneinfo/America/Rosario
	share/zoneinfo/America/Anguilla
	share/zoneinfo/America/Anchorage
	share/zoneinfo/America/Metlakatla
	share/zoneinfo/America/Jamaica
	share/zoneinfo/America/St_Kitts
	share/zoneinfo/America/Cayenne
	share/zoneinfo/America/Recife
	share/zoneinfo/America/St_Vincent
	share/zoneinfo/America/El_Salvador
	share/zoneinfo/America/Kralendijk
	share/zoneinfo/America/Chihuahua
	share/zoneinfo/America/Araguaina
	share/zoneinfo/America/Curacao
	share/zoneinfo/America/Porto_Acre
	share/zoneinfo/America/Boa_Vista
	share/zoneinfo/America/Manaus
	share/zoneinfo/America/Ojinaga
	share/zoneinfo/America/Managua
	share/zoneinfo/America/Chicago
	share/zoneinfo/America/Sao_Paulo
	share/zoneinfo/America/Asuncion
	share/zoneinfo/America/Guadeloupe
	share/zoneinfo/America/Martinique
	share/zoneinfo/America/Boise
	share/zoneinfo/America/Godthab
	share/zoneinfo/America/Danmarkshavn
	share/zoneinfo/America/Rankin_Inlet
	share/zoneinfo/America/Guayaquil
	share/zoneinfo/America/Iqaluit
	share/zoneinfo/America/Barbados
	share/zoneinfo/America/Dominica
	share/zoneinfo/America/Indianapolis
	share/zoneinfo/America/St_Johns
	share/zoneinfo/America/Buenos_Aires
	share/zoneinfo/America/Halifax
	share/zoneinfo/America/Catamarca
	share/zoneinfo/America/Ensenada
	share/zoneinfo/America/Vancouver
	share/zoneinfo/America/Atikokan
	share/zoneinfo/America/Regina
	share/zoneinfo/America/Grand_Turk
	share/zoneinfo/America/St_Barthelemy
	share/zoneinfo/America/Nome
	share/zoneinfo/America/Montserrat
	share/zoneinfo/America/Port-au-Prince
	share/zoneinfo/America/Winnipeg
	share/zoneinfo/America/Virgin
	share/zoneinfo/America/Fort_Wayne
	share/zoneinfo/America/Tegucigalpa
	share/zoneinfo/America/Mendoza
	share/zoneinfo/America/Paramaribo
	share/zoneinfo/America/Belem
	share/zoneinfo/America/Louisville
	share/zoneinfo/America/Merida
	share/zoneinfo/America/Creston
	share/zoneinfo/America/La_Paz
	share/zoneinfo/America/Coral_Harbour
	share/zoneinfo/America/New_York
	share/zoneinfo/America/Port_of_Spain
	share/zoneinfo/America/St_Thomas
	share/zoneinfo/America/Puerto_Rico
	share/zoneinfo/America/Matamoros
	share/zoneinfo/America/Santo_Domingo
	share/zoneinfo/America/Edmonton
	share/zoneinfo/America/Knox_IN
	share/zoneinfo/America/Antigua
	share/zoneinfo/America/Tortola
	share/zoneinfo/America/Dawson_Creek
	share/zoneinfo/America/Indiana
	share/zoneinfo/America/Indiana/Winamac
	share/zoneinfo/America/Indiana/Indianapolis
	share/zoneinfo/America/Indiana/Petersburg
	share/zoneinfo/America/Indiana/Knox
	share/zoneinfo/America/Indiana/Vevay
	share/zoneinfo/America/Indiana/Marengo
	share/zoneinfo/America/Indiana/Vincennes
	share/zoneinfo/America/Indiana/Tell_City
	share/zoneinfo/America/Santa_Isabel
	share/zoneinfo/America/Pangnirtung
	share/zoneinfo/America/Los_Angeles
	share/zoneinfo/America/Cancun
	share/zoneinfo/America/Toronto
	share/zoneinfo/America/Guatemala
	share/zoneinfo/America/Cayman
	share/zoneinfo/America/Miquelon
	share/zoneinfo/America/Goose_Bay
	share/zoneinfo/America/Eirunepe
	share/zoneinfo/America/Resolute
	share/zoneinfo/America/Cordoba
	share/zoneinfo/America/Aruba
	share/zoneinfo/America/Santiago
	share/zoneinfo/America/Lower_Princes
	share/zoneinfo/America/Monterrey
	share/zoneinfo/America/Costa_Rica
	share/zoneinfo/America/Sitka
	share/zoneinfo/America/St_Lucia
	share/zoneinfo/America/Nipigon
	share/zoneinfo/America/Panama
	share/zoneinfo/America/Belize
	share/zoneinfo/America/Marigot
	share/zoneinfo/America/Porto_Velho
	share/zoneinfo/America/Bahia
	share/zoneinfo/America/Rainy_River
	share/zoneinfo/America/Denver
	share/zoneinfo/America/Kentucky
	share/zoneinfo/America/Kentucky/Louisville
	share/zoneinfo/America/Kentucky/Monticello
	share/zoneinfo/America/Moncton
	share/zoneinfo/America/Thunder_Bay
	share/zoneinfo/America/Yakutat
	share/zoneinfo/America/Cuiaba
	share/zoneinfo/America/Caracas
	share/zoneinfo/America/Glace_Bay
	share/zoneinfo/America/Guyana
	share/zoneinfo/America/Cambridge_Bay
	share/zoneinfo/America/Fortaleza
	share/zoneinfo/America/Montreal
	share/zoneinfo/America/Havana
	share/zoneinfo/America/Menominee
	share/zoneinfo/America/Shiprock
	share/zoneinfo/America/Maceio
	share/zoneinfo/America/Bogota
	share/zoneinfo/America/Jujuy
	share/zoneinfo/America/Bahia_Banderas
	share/zoneinfo/America/Whitehorse
	share/zoneinfo/America/Dawson
	share/zoneinfo/America/Juneau
	share/zoneinfo/America/Phoenix
	share/zoneinfo/America/Detroit
	share/zoneinfo/America/Inuvik
	share/zoneinfo/America/Adak
	share/zoneinfo/America/Hermosillo
	share/zoneinfo/America/Thule
	share/zoneinfo/America/Noronha
	share/zoneinfo/America/North_Dakota
	share/zoneinfo/America/North_Dakota/Center
	share/zoneinfo/America/North_Dakota/New_Salem
	share/zoneinfo/America/North_Dakota/Beulah
	share/zoneinfo/America/Lima
	share/zoneinfo/America/Montevideo
	share/zoneinfo/America/Scoresbysund
	share/zoneinfo/America/Tijuana
	share/zoneinfo/America/Yellowknife
	share/zoneinfo/America/Mexico_City
	share/zoneinfo/NZ
	share/zoneinfo/PRC
	share/zoneinfo/WET
	share/zoneinfo/GMT+0
	share/zoneinfo/Pacific
	share/zoneinfo/Pacific/Samoa
	share/zoneinfo/Pacific/Johnston
	share/zoneinfo/Pacific/Guam
	share/zoneinfo/Pacific/Guadalcanal
	share/zoneinfo/Pacific/Majuro
	share/zoneinfo/Pacific/Truk
	share/zoneinfo/Pacific/Auckland
	share/zoneinfo/Pacific/Fakaofo
	share/zoneinfo/Pacific/Honolulu
	share/zoneinfo/Pacific/Nauru
	share/zoneinfo/Pacific/Kiritimati
	share/zoneinfo/Pacific/Funafuti
	share/zoneinfo/Pacific/Tahiti
	share/zoneinfo/Pacific/Chatham
	share/zoneinfo/Pacific/Norfolk
	share/zoneinfo/Pacific/Enderbury
	share/zoneinfo/Pacific/Kosrae
	share/zoneinfo/Pacific/Apia
	share/zoneinfo/Pacific/Saipan
	share/zoneinfo/Pacific/Chuuk
	share/zoneinfo/Pacific/Pitcairn
	share/zoneinfo/Pacific/Ponape
	share/zoneinfo/Pacific/Yap
	share/zoneinfo/Pacific/Wallis
	share/zoneinfo/Pacific/Galapagos
	share/zoneinfo/Pacific/Pohnpei
	share/zoneinfo/Pacific/Tongatapu
	share/zoneinfo/Pacific/Easter
	share/zoneinfo/Pacific/Wake
	share/zoneinfo/Pacific/Pago_Pago
	share/zoneinfo/Pacific/Marquesas
	share/zoneinfo/Pacific/Noumea
	share/zoneinfo/Pacific/Tarawa
	share/zoneinfo/Pacific/Gambier
	share/zoneinfo/Pacific/Niue
	share/zoneinfo/Pacific/Palau
	share/zoneinfo/Pacific/Kwajalein
	share/zoneinfo/Pacific/Midway
	share/zoneinfo/Pacific/Rarotonga
	share/zoneinfo/Pacific/Fiji
	share/zoneinfo/Pacific/Port_Moresby
	share/zoneinfo/Pacific/Efate
	share/zoneinfo/zone.tab
	share/zoneinfo/Japan
	share/zoneinfo/Israel
	share/zoneinfo/UTC
	share/zoneinfo/Brazil
	share/zoneinfo/Brazil/Acre
	share/zoneinfo/Brazil/DeNoronha
	share/zoneinfo/Brazil/East
	share/zoneinfo/Brazil/West
	share/zoneinfo/Antarctica
	share/zoneinfo/Antarctica/Macquarie
	share/zoneinfo/Antarctica/Palmer
	share/zoneinfo/Antarctica/DumontDUrville
	share/zoneinfo/Antarctica/South_Pole
	share/zoneinfo/Antarctica/Vostok
	share/zoneinfo/Antarctica/McMurdo
	share/zoneinfo/Antarctica/Casey
	share/zoneinfo/Antarctica/Mawson
	share/zoneinfo/Antarctica/Davis
	share/zoneinfo/Antarctica/Syowa
	share/zoneinfo/Antarctica/Rothera
	share/zoneinfo/HST
	share/zoneinfo/Poland
	share/zoneinfo/posixrules
	share/zoneinfo/Canada
	share/zoneinfo/Canada/Atlantic
	share/zoneinfo/Canada/Eastern
	share/zoneinfo/Canada/Central
	share/zoneinfo/Canada/Mountain
	share/zoneinfo/Canada/Yukon
	share/zoneinfo/Canada/Pacific
	share/zoneinfo/Canada/Saskatchewan
	share/zoneinfo/Canada/East-Saskatchewan
	share/zoneinfo/Canada/Newfoundland
	share/zoneinfo/posix
	share/zoneinfo/posix/US
	share/zoneinfo/posix/US/Samoa
	share/zoneinfo/posix/US/Alaska
	share/zoneinfo/posix/US/Hawaii
	share/zoneinfo/posix/US/Arizona
	share/zoneinfo/posix/US/Indiana-Starke
	share/zoneinfo/posix/US/Michigan
	share/zoneinfo/posix/US/Eastern
	share/zoneinfo/posix/US/Central
	share/zoneinfo/posix/US/East-Indiana
	share/zoneinfo/posix/US/Mountain
	share/zoneinfo/posix/US/Pacific
	share/zoneinfo/posix/US/Aleutian
	share/zoneinfo/posix/US/Pacific-New
	share/zoneinfo/posix/Universal
	share/zoneinfo/posix/Asia
	share/zoneinfo/posix/Asia/Tbilisi
	share/zoneinfo/posix/Asia/Jakarta
	share/zoneinfo/posix/Asia/Riyadh89
	share/zoneinfo/posix/Asia/Dubai
	share/zoneinfo/posix/Asia/Colombo
	share/zoneinfo/posix/Asia/Vientiane
	share/zoneinfo/posix/Asia/Harbin
	share/zoneinfo/posix/Asia/Taipei
	share/zoneinfo/posix/Asia/Phnom_Penh
	share/zoneinfo/posix/Asia/Ujung_Pandang
	share/zoneinfo/posix/Asia/Makassar
	share/zoneinfo/posix/Asia/Almaty
	share/zoneinfo/posix/Asia/Baghdad
	share/zoneinfo/posix/Asia/Aqtau
	share/zoneinfo/posix/Asia/Irkutsk
	share/zoneinfo/posix/Asia/Chungking
	share/zoneinfo/posix/Asia/Bishkek
	share/zoneinfo/posix/Asia/Shanghai
	share/zoneinfo/posix/Asia/Saigon
	share/zoneinfo/posix/Asia/Tashkent
	share/zoneinfo/posix/Asia/Yerevan
	share/zoneinfo/posix/Asia/Ashkhabad
	share/zoneinfo/posix/Asia/Kamchatka
	share/zoneinfo/posix/Asia/Baku
	share/zoneinfo/posix/Asia/Tel_Aviv
	share/zoneinfo/posix/Asia/Krasnoyarsk
	share/zoneinfo/posix/Asia/Nicosia
	share/zoneinfo/posix/Asia/Muscat
	share/zoneinfo/posix/Asia/Qatar
	share/zoneinfo/posix/Asia/Kathmandu
	share/zoneinfo/posix/Asia/Hovd
	share/zoneinfo/posix/Asia/Ho_Chi_Minh
	share/zoneinfo/posix/Asia/Gaza
	share/zoneinfo/posix/Asia/Singapore
	share/zoneinfo/posix/Asia/Dacca
	share/zoneinfo/posix/Asia/Anadyr
	share/zoneinfo/posix/Asia/Riyadh
	share/zoneinfo/posix/Asia/Beirut
	share/zoneinfo/posix/Asia/Pyongyang
	share/zoneinfo/posix/Asia/Thimbu
	share/zoneinfo/posix/Asia/Kolkata
	share/zoneinfo/posix/Asia/Urumqi
	share/zoneinfo/posix/Asia/Jayapura
	share/zoneinfo/posix/Asia/Riyadh88
	share/zoneinfo/posix/Asia/Novosibirsk
	share/zoneinfo/posix/Asia/Hong_Kong
	share/zoneinfo/posix/Asia/Yekaterinburg
	share/zoneinfo/posix/Asia/Dhaka
	share/zoneinfo/posix/Asia/Oral
	share/zoneinfo/posix/Asia/Manila
	share/zoneinfo/posix/Asia/Tokyo
	share/zoneinfo/posix/Asia/Riyadh87
	share/zoneinfo/posix/Asia/Rangoon
	share/zoneinfo/posix/Asia/Tehran
	share/zoneinfo/posix/Asia/Ashgabat
	share/zoneinfo/posix/Asia/Ust-Nera
	share/zoneinfo/posix/Asia/Vladivostok
	share/zoneinfo/posix/Asia/Yakutsk
	share/zoneinfo/posix/Asia/Bahrain
	share/zoneinfo/posix/Asia/Macao
	share/zoneinfo/posix/Asia/Ulaanbaatar
	share/zoneinfo/posix/Asia/Kuwait
	share/zoneinfo/posix/Asia/Bangkok
	share/zoneinfo/posix/Asia/Chongqing
	share/zoneinfo/posix/Asia/Brunei
	share/zoneinfo/posix/Asia/Aden
	share/zoneinfo/posix/Asia/Kabul
	share/zoneinfo/posix/Asia/Choibalsan
	share/zoneinfo/posix/Asia/Istanbul
	share/zoneinfo/posix/Asia/Samarkand
	share/zoneinfo/posix/Asia/Karachi
	share/zoneinfo/posix/Asia/Damascus
	share/zoneinfo/posix/Asia/Novokuznetsk
	share/zoneinfo/posix/Asia/Aqtobe
	share/zoneinfo/posix/Asia/Jerusalem
	share/zoneinfo/posix/Asia/Dili
	share/zoneinfo/posix/Asia/Dushanbe
	share/zoneinfo/posix/Asia/Amman
	share/zoneinfo/posix/Asia/Ulan_Bator
	share/zoneinfo/posix/Asia/Kashgar
	share/zoneinfo/posix/Asia/Calcutta
	share/zoneinfo/posix/Asia/Omsk
	share/zoneinfo/posix/Asia/Kuching
	share/zoneinfo/posix/Asia/Kuala_Lumpur
	share/zoneinfo/posix/Asia/Pontianak
	share/zoneinfo/posix/Asia/Katmandu
	share/zoneinfo/posix/Asia/Seoul
	share/zoneinfo/posix/Asia/Qyzylorda
	share/zoneinfo/posix/Asia/Thimphu
	share/zoneinfo/posix/Asia/Magadan
	share/zoneinfo/posix/Asia/Macau
	share/zoneinfo/posix/Asia/Khandyga
	share/zoneinfo/posix/Asia/Sakhalin
	share/zoneinfo/posix/Asia/Hebron
	share/zoneinfo/posix/EST
	share/zoneinfo/posix/Jamaica
	share/zoneinfo/posix/NZ-CHAT
	share/zoneinfo/posix/Iran
	share/zoneinfo/posix/GB
	share/zoneinfo/posix/Mideast
	share/zoneinfo/posix/Mideast/Riyadh89
	share/zoneinfo/posix/Mideast/Riyadh88
	share/zoneinfo/posix/Mideast/Riyadh87
	share/zoneinfo/posix/Europe
	share/zoneinfo/posix/Europe/Sofia
	share/zoneinfo/posix/Europe/Vienna
	share/zoneinfo/posix/Europe/Moscow
	share/zoneinfo/posix/Europe/Monaco
	share/zoneinfo/posix/Europe/Warsaw
	share/zoneinfo/posix/Europe/Lisbon
	share/zoneinfo/posix/Europe/Chisinau
	share/zoneinfo/posix/Europe/Prague
	share/zoneinfo/posix/Europe/Belgrade
	share/zoneinfo/posix/Europe/Vatican
	share/zoneinfo/posix/Europe/Volgograd
	share/zoneinfo/posix/Europe/Malta
	share/zoneinfo/posix/Europe/Vaduz
	share/zoneinfo/posix/Europe/Nicosia
	share/zoneinfo/posix/Europe/Gibraltar
	share/zoneinfo/posix/Europe/Paris
	share/zoneinfo/posix/Europe/San_Marino
	share/zoneinfo/posix/Europe/Brussels
	share/zoneinfo/posix/Europe/Rome
	share/zoneinfo/posix/Europe/Minsk
	share/zoneinfo/posix/Europe/Isle_of_Man
	share/zoneinfo/posix/Europe/Kaliningrad
	share/zoneinfo/posix/Europe/Simferopol
	share/zoneinfo/posix/Europe/Tirane
	share/zoneinfo/posix/Europe/Sarajevo
	share/zoneinfo/posix/Europe/Stockholm
	share/zoneinfo/posix/Europe/Vilnius
	share/zoneinfo/posix/Europe/Copenhagen
	share/zoneinfo/posix/Europe/Skopje
	share/zoneinfo/posix/Europe/Kiev
	share/zoneinfo/posix/Europe/Amsterdam
	share/zoneinfo/posix/Europe/Luxembourg
	share/zoneinfo/posix/Europe/Bratislava
	share/zoneinfo/posix/Europe/Riga
	share/zoneinfo/posix/Europe/London
	share/zoneinfo/posix/Europe/Athens
	share/zoneinfo/posix/Europe/Samara
	share/zoneinfo/posix/Europe/Mariehamn
	share/zoneinfo/posix/Europe/Jersey
	share/zoneinfo/posix/Europe/Uzhgorod
	share/zoneinfo/posix/Europe/Istanbul
	share/zoneinfo/posix/Europe/Belfast
	share/zoneinfo/posix/Europe/Dublin
	share/zoneinfo/posix/Europe/Zagreb
	share/zoneinfo/posix/Europe/Zaporozhye
	share/zoneinfo/posix/Europe/Helsinki
	share/zoneinfo/posix/Europe/Bucharest
	share/zoneinfo/posix/Europe/Andorra
	share/zoneinfo/posix/Europe/Oslo
	share/zoneinfo/posix/Europe/Ljubljana
	share/zoneinfo/posix/Europe/Podgorica
	share/zoneinfo/posix/Europe/Madrid
	share/zoneinfo/posix/Europe/Berlin
	share/zoneinfo/posix/Europe/Busingen
	share/zoneinfo/posix/Europe/Budapest
	share/zoneinfo/posix/Europe/Guernsey
	share/zoneinfo/posix/Europe/Tallinn
	share/zoneinfo/posix/Europe/Tiraspol
	share/zoneinfo/posix/Europe/Zurich
	share/zoneinfo/posix/Factory
	share/zoneinfo/posix/ROC
	share/zoneinfo/posix/UCT
	share/zoneinfo/posix/GMT0
	share/zoneinfo/posix/Atlantic
	share/zoneinfo/posix/Atlantic/Faeroe
	share/zoneinfo/posix/Atlantic/Cape_Verde
	share/zoneinfo/posix/Atlantic/South_Georgia
	share/zoneinfo/posix/Atlantic/Stanley
	share/zoneinfo/posix/Atlantic/Bermuda
	share/zoneinfo/posix/Atlantic/Faroe
	share/zoneinfo/posix/Atlantic/Jan_Mayen
	share/zoneinfo/posix/Atlantic/Reykjavik
	share/zoneinfo/posix/Atlantic/St_Helena
	share/zoneinfo/posix/Atlantic/Canary
	share/zoneinfo/posix/Atlantic/Azores
	share/zoneinfo/posix/Atlantic/Madeira
	share/zoneinfo/posix/Zulu
	share/zoneinfo/posix/EST5EDT
	share/zoneinfo/posix/MST
	share/zoneinfo/posix/Navajo
	share/zoneinfo/posix/Hongkong
	share/zoneinfo/posix/Egypt
	share/zoneinfo/posix/PST8PDT
	share/zoneinfo/posix/Chile
	share/zoneinfo/posix/Chile/Continental
	share/zoneinfo/posix/Chile/EasterIsland
	share/zoneinfo/posix/Singapore
	share/zoneinfo/posix/Indian
	share/zoneinfo/posix/Indian/Mahe
	share/zoneinfo/posix/Indian/Kerguelen
	share/zoneinfo/posix/Indian/Mayotte
	share/zoneinfo/posix/Indian/Cocos
	share/zoneinfo/posix/Indian/Chagos
	share/zoneinfo/posix/Indian/Antananarivo
	share/zoneinfo/posix/Indian/Mauritius
	share/zoneinfo/posix/Indian/Comoro
	share/zoneinfo/posix/Indian/Christmas
	share/zoneinfo/posix/Indian/Maldives
	share/zoneinfo/posix/Indian/Reunion
	share/zoneinfo/posix/Libya
	share/zoneinfo/posix/Etc
	share/zoneinfo/posix/Etc/Universal
	share/zoneinfo/posix/Etc/GMT+2
	share/zoneinfo/posix/Etc/GMT+12
	share/zoneinfo/posix/Etc/UCT
	share/zoneinfo/posix/Etc/GMT0
	share/zoneinfo/posix/Etc/GMT-8
	share/zoneinfo/posix/Etc/GMT+4
	share/zoneinfo/posix/Etc/GMT+8
	share/zoneinfo/posix/Etc/GMT-10
	share/zoneinfo/posix/Etc/GMT+11
	share/zoneinfo/posix/Etc/Zulu
	share/zoneinfo/posix/Etc/GMT-12
	share/zoneinfo/posix/Etc/GMT-3
	share/zoneinfo/posix/Etc/GMT-7
	share/zoneinfo/posix/Etc/GMT-11
	share/zoneinfo/posix/Etc/GMT-4
	share/zoneinfo/posix/Etc/GMT+5
	share/zoneinfo/posix/Etc/GMT-2
	share/zoneinfo/posix/Etc/GMT-13
	share/zoneinfo/posix/Etc/GMT+9
	share/zoneinfo/posix/Etc/GMT-14
	share/zoneinfo/posix/Etc/Greenwich
	share/zoneinfo/posix/Etc/GMT+0
	share/zoneinfo/posix/Etc/GMT+10
	share/zoneinfo/posix/Etc/UTC
	share/zoneinfo/posix/Etc/GMT+7
	share/zoneinfo/posix/Etc/GMT-6
	share/zoneinfo/posix/Etc/GMT-0
	share/zoneinfo/posix/Etc/GMT+3
	share/zoneinfo/posix/Etc/GMT+6
	share/zoneinfo/posix/Etc/GMT
	share/zoneinfo/posix/Etc/GMT+1
	share/zoneinfo/posix/Etc/GMT-5
	share/zoneinfo/posix/Etc/GMT-1
	share/zoneinfo/posix/Etc/GMT-9
	share/zoneinfo/posix/W-SU
	share/zoneinfo/posix/Africa
	share/zoneinfo/posix/Africa/Asmera
	share/zoneinfo/posix/Africa/Accra
	share/zoneinfo/posix/Africa/Nouakchott
	share/zoneinfo/posix/Africa/Abidjan
	share/zoneinfo/posix/Africa/Banjul
	share/zoneinfo/posix/Africa/Timbuktu
	share/zoneinfo/posix/Africa/Maseru
	share/zoneinfo/posix/Africa/Sao_Tome
	share/zoneinfo/posix/Africa/Douala
	share/zoneinfo/posix/Africa/Dakar
	share/zoneinfo/posix/Africa/Porto-Novo
	share/zoneinfo/posix/Africa/Juba
	share/zoneinfo/posix/Africa/Mbabane
	share/zoneinfo/posix/Africa/Johannesburg
	share/zoneinfo/posix/Africa/Cairo
	share/zoneinfo/posix/Africa/Gaborone
	share/zoneinfo/posix/Africa/Tripoli
	share/zoneinfo/posix/Africa/Algiers
	share/zoneinfo/posix/Africa/Ndjamena
	share/zoneinfo/posix/Africa/Windhoek
	share/zoneinfo/posix/Africa/Conakry
	share/zoneinfo/posix/Africa/Maputo
	share/zoneinfo/posix/Africa/Djibouti
	share/zoneinfo/posix/Africa/Dar_es_Salaam
	share/zoneinfo/posix/Africa/Brazzaville
	share/zoneinfo/posix/Africa/Ouagadougou
	share/zoneinfo/posix/Africa/Harare
	share/zoneinfo/posix/Africa/Ceuta
	share/zoneinfo/posix/Africa/Casablanca
	share/zoneinfo/posix/Africa/Bamako
	share/zoneinfo/posix/Africa/Bissau
	share/zoneinfo/posix/Africa/El_Aaiun
	share/zoneinfo/posix/Africa/Bujumbura
	share/zoneinfo/posix/Africa/Lagos
	share/zoneinfo/posix/Africa/Luanda
	share/zoneinfo/posix/Africa/Lome
	share/zoneinfo/posix/Africa/Lusaka
	share/zoneinfo/posix/Africa/Addis_Ababa
	share/zoneinfo/posix/Africa/Tunis
	share/zoneinfo/posix/Africa/Kigali
	share/zoneinfo/posix/Africa/Khartoum
	share/zoneinfo/posix/Africa/Malabo
	share/zoneinfo/posix/Africa/Bangui
	share/zoneinfo/posix/Africa/Mogadishu
	share/zoneinfo/posix/Africa/Monrovia
	share/zoneinfo/posix/Africa/Kinshasa
	share/zoneinfo/posix/Africa/Blantyre
	share/zoneinfo/posix/Africa/Kampala
	share/zoneinfo/posix/Africa/Niamey
	share/zoneinfo/posix/Africa/Nairobi
	share/zoneinfo/posix/Africa/Freetown
	share/zoneinfo/posix/Africa/Lubumbashi
	share/zoneinfo/posix/Africa/Libreville
	share/zoneinfo/posix/Africa/Asmara
	share/zoneinfo/posix/MST7MDT
	share/zoneinfo/posix/Greenwich
	share/zoneinfo/posix/America
	share/zoneinfo/posix/America/Mazatlan
	share/zoneinfo/posix/America/Nassau
	share/zoneinfo/posix/America/Swift_Current
	share/zoneinfo/posix/America/Campo_Grande
	share/zoneinfo/posix/America/Blanc-Sablon
	share/zoneinfo/posix/America/Santarem
	share/zoneinfo/posix/America/Grenada
	share/zoneinfo/posix/America/Argentina
	share/zoneinfo/posix/America/Argentina/Rio_Gallegos
	share/zoneinfo/posix/America/Argentina/Tucuman
	share/zoneinfo/posix/America/Argentina/Buenos_Aires
	share/zoneinfo/posix/America/Argentina/Catamarca
	share/zoneinfo/posix/America/Argentina/Mendoza
	share/zoneinfo/posix/America/Argentina/San_Luis
	share/zoneinfo/posix/America/Argentina/Salta
	share/zoneinfo/posix/America/Argentina/ComodRivadavia
	share/zoneinfo/posix/America/Argentina/Cordoba
	share/zoneinfo/posix/America/Argentina/Ushuaia
	share/zoneinfo/posix/America/Argentina/Jujuy
	share/zoneinfo/posix/America/Argentina/La_Rioja
	share/zoneinfo/posix/America/Argentina/San_Juan
	share/zoneinfo/posix/America/Rio_Branco
	share/zoneinfo/posix/America/Atka
	share/zoneinfo/posix/America/Rosario
	share/zoneinfo/posix/America/Anguilla
	share/zoneinfo/posix/America/Anchorage
	share/zoneinfo/posix/America/Metlakatla
	share/zoneinfo/posix/America/Jamaica
	share/zoneinfo/posix/America/St_Kitts
	share/zoneinfo/posix/America/Cayenne
	share/zoneinfo/posix/America/Recife
	share/zoneinfo/posix/America/St_Vincent
	share/zoneinfo/posix/America/El_Salvador
	share/zoneinfo/posix/America/Kralendijk
	share/zoneinfo/posix/America/Chihuahua
	share/zoneinfo/posix/America/Araguaina
	share/zoneinfo/posix/America/Curacao
	share/zoneinfo/posix/America/Porto_Acre
	share/zoneinfo/posix/America/Boa_Vista
	share/zoneinfo/posix/America/Manaus
	share/zoneinfo/posix/America/Ojinaga
	share/zoneinfo/posix/America/Managua
	share/zoneinfo/posix/America/Chicago
	share/zoneinfo/posix/America/Sao_Paulo
	share/zoneinfo/posix/America/Asuncion
	share/zoneinfo/posix/America/Guadeloupe
	share/zoneinfo/posix/America/Martinique
	share/zoneinfo/posix/America/Boise
	share/zoneinfo/posix/America/Godthab
	share/zoneinfo/posix/America/Danmarkshavn
	share/zoneinfo/posix/America/Rankin_Inlet
	share/zoneinfo/posix/America/Guayaquil
	share/zoneinfo/posix/America/Iqaluit
	share/zoneinfo/posix/America/Barbados
	share/zoneinfo/posix/America/Dominica
	share/zoneinfo/posix/America/Indianapolis
	share/zoneinfo/posix/America/St_Johns
	share/zoneinfo/posix/America/Buenos_Aires
	share/zoneinfo/posix/America/Halifax
	share/zoneinfo/posix/America/Catamarca
	share/zoneinfo/posix/America/Ensenada
	share/zoneinfo/posix/America/Vancouver
	share/zoneinfo/posix/America/Atikokan
	share/zoneinfo/posix/America/Regina
	share/zoneinfo/posix/America/Grand_Turk
	share/zoneinfo/posix/America/St_Barthelemy
	share/zoneinfo/posix/America/Nome
	share/zoneinfo/posix/America/Montserrat
	share/zoneinfo/posix/America/Port-au-Prince
	share/zoneinfo/posix/America/Winnipeg
	share/zoneinfo/posix/America/Virgin
	share/zoneinfo/posix/America/Fort_Wayne
	share/zoneinfo/posix/America/Tegucigalpa
	share/zoneinfo/posix/America/Mendoza
	share/zoneinfo/posix/America/Paramaribo
	share/zoneinfo/posix/America/Belem
	share/zoneinfo/posix/America/Louisville
	share/zoneinfo/posix/America/Merida
	share/zoneinfo/posix/America/Creston
	share/zoneinfo/posix/America/La_Paz
	share/zoneinfo/posix/America/Coral_Harbour
	share/zoneinfo/posix/America/New_York
	share/zoneinfo/posix/America/Port_of_Spain
	share/zoneinfo/posix/America/St_Thomas
	share/zoneinfo/posix/America/Puerto_Rico
	share/zoneinfo/posix/America/Matamoros
	share/zoneinfo/posix/America/Santo_Domingo
	share/zoneinfo/posix/America/Edmonton
	share/zoneinfo/posix/America/Knox_IN
	share/zoneinfo/posix/America/Antigua
	share/zoneinfo/posix/America/Tortola
	share/zoneinfo/posix/America/Dawson_Creek
	share/zoneinfo/posix/America/Indiana
	share/zoneinfo/posix/America/Indiana/Winamac
	share/zoneinfo/posix/America/Indiana/Indianapolis
	share/zoneinfo/posix/America/Indiana/Petersburg
	share/zoneinfo/posix/America/Indiana/Knox
	share/zoneinfo/posix/America/Indiana/Vevay
	share/zoneinfo/posix/America/Indiana/Marengo
	share/zoneinfo/posix/America/Indiana/Vincennes
	share/zoneinfo/posix/America/Indiana/Tell_City
	share/zoneinfo/posix/America/Santa_Isabel
	share/zoneinfo/posix/America/Pangnirtung
	share/zoneinfo/posix/America/Los_Angeles
	share/zoneinfo/posix/America/Cancun
	share/zoneinfo/posix/America/Toronto
	share/zoneinfo/posix/America/Guatemala
	share/zoneinfo/posix/America/Cayman
	share/zoneinfo/posix/America/Miquelon
	share/zoneinfo/posix/America/Goose_Bay
	share/zoneinfo/posix/America/Eirunepe
	share/zoneinfo/posix/America/Resolute
	share/zoneinfo/posix/America/Cordoba
	share/zoneinfo/posix/America/Aruba
	share/zoneinfo/posix/America/Santiago
	share/zoneinfo/posix/America/Lower_Princes
	share/zoneinfo/posix/America/Monterrey
	share/zoneinfo/posix/America/Costa_Rica
	share/zoneinfo/posix/America/Sitka
	share/zoneinfo/posix/America/St_Lucia
	share/zoneinfo/posix/America/Nipigon
	share/zoneinfo/posix/America/Panama
	share/zoneinfo/posix/America/Belize
	share/zoneinfo/posix/America/Marigot
	share/zoneinfo/posix/America/Porto_Velho
	share/zoneinfo/posix/America/Bahia
	share/zoneinfo/posix/America/Rainy_River
	share/zoneinfo/posix/America/Denver
	share/zoneinfo/posix/America/Kentucky
	share/zoneinfo/posix/America/Kentucky/Louisville
	share/zoneinfo/posix/America/Kentucky/Monticello
	share/zoneinfo/posix/America/Moncton
	share/zoneinfo/posix/America/Thunder_Bay
	share/zoneinfo/posix/America/Yakutat
	share/zoneinfo/posix/America/Cuiaba
	share/zoneinfo/posix/America/Caracas
	share/zoneinfo/posix/America/Glace_Bay
	share/zoneinfo/posix/America/Guyana
	share/zoneinfo/posix/America/Cambridge_Bay
	share/zoneinfo/posix/America/Fortaleza
	share/zoneinfo/posix/America/Montreal
	share/zoneinfo/posix/America/Havana
	share/zoneinfo/posix/America/Menominee
	share/zoneinfo/posix/America/Shiprock
	share/zoneinfo/posix/America/Maceio
	share/zoneinfo/posix/America/Bogota
	share/zoneinfo/posix/America/Jujuy
	share/zoneinfo/posix/America/Bahia_Banderas
	share/zoneinfo/posix/America/Whitehorse
	share/zoneinfo/posix/America/Dawson
	share/zoneinfo/posix/America/Juneau
	share/zoneinfo/posix/America/Phoenix
	share/zoneinfo/posix/America/Detroit
	share/zoneinfo/posix/America/Inuvik
	share/zoneinfo/posix/America/Adak
	share/zoneinfo/posix/America/Hermosillo
	share/zoneinfo/posix/America/Thule
	share/zoneinfo/posix/America/Noronha
	share/zoneinfo/posix/America/North_Dakota
	share/zoneinfo/posix/America/North_Dakota/Center
	share/zoneinfo/posix/America/North_Dakota/New_Salem
	share/zoneinfo/posix/America/North_Dakota/Beulah
	share/zoneinfo/posix/America/Lima
	share/zoneinfo/posix/America/Montevideo
	share/zoneinfo/posix/America/Scoresbysund
	share/zoneinfo/posix/America/Tijuana
	share/zoneinfo/posix/America/Yellowknife
	share/zoneinfo/posix/America/Mexico_City
	share/zoneinfo/posix/NZ
	share/zoneinfo/posix/PRC
	share/zoneinfo/posix/WET
	share/zoneinfo/posix/GMT+0
	share/zoneinfo/posix/Pacific
	share/zoneinfo/posix/Pacific/Samoa
	share/zoneinfo/posix/Pacific/Johnston
	share/zoneinfo/posix/Pacific/Guam
	share/zoneinfo/posix/Pacific/Guadalcanal
	share/zoneinfo/posix/Pacific/Majuro
	share/zoneinfo/posix/Pacific/Truk
	share/zoneinfo/posix/Pacific/Auckland
	share/zoneinfo/posix/Pacific/Fakaofo
	share/zoneinfo/posix/Pacific/Honolulu
	share/zoneinfo/posix/Pacific/Nauru
	share/zoneinfo/posix/Pacific/Kiritimati
	share/zoneinfo/posix/Pacific/Funafuti
	share/zoneinfo/posix/Pacific/Tahiti
	share/zoneinfo/posix/Pacific/Chatham
	share/zoneinfo/posix/Pacific/Norfolk
	share/zoneinfo/posix/Pacific/Enderbury
	share/zoneinfo/posix/Pacific/Kosrae
	share/zoneinfo/posix/Pacific/Apia
	share/zoneinfo/posix/Pacific/Saipan
	share/zoneinfo/posix/Pacific/Chuuk
	share/zoneinfo/posix/Pacific/Pitcairn
	share/zoneinfo/posix/Pacific/Ponape
	share/zoneinfo/posix/Pacific/Yap
	share/zoneinfo/posix/Pacific/Wallis
	share/zoneinfo/posix/Pacific/Galapagos
	share/zoneinfo/posix/Pacific/Pohnpei
	share/zoneinfo/posix/Pacific/Tongatapu
	share/zoneinfo/posix/Pacific/Easter
	share/zoneinfo/posix/Pacific/Wake
	share/zoneinfo/posix/Pacific/Pago_Pago
	share/zoneinfo/posix/Pacific/Marquesas
	share/zoneinfo/posix/Pacific/Noumea
	share/zoneinfo/posix/Pacific/Tarawa
	share/zoneinfo/posix/Pacific/Gambier
	share/zoneinfo/posix/Pacific/Niue
	share/zoneinfo/posix/Pacific/Palau
	share/zoneinfo/posix/Pacific/Kwajalein
	share/zoneinfo/posix/Pacific/Midway
	share/zoneinfo/posix/Pacific/Rarotonga
	share/zoneinfo/posix/Pacific/Fiji
	share/zoneinfo/posix/Pacific/Port_Moresby
	share/zoneinfo/posix/Pacific/Efate
	share/zoneinfo/posix/Japan
	share/zoneinfo/posix/Israel
	share/zoneinfo/posix/UTC
	share/zoneinfo/posix/Brazil
	share/zoneinfo/posix/Brazil/Acre
	share/zoneinfo/posix/Brazil/DeNoronha
	share/zoneinfo/posix/Brazil/East
	share/zoneinfo/posix/Brazil/West
	share/zoneinfo/posix/Antarctica
	share/zoneinfo/posix/Antarctica/Macquarie
	share/zoneinfo/posix/Antarctica/Palmer
	share/zoneinfo/posix/Antarctica/DumontDUrville
	share/zoneinfo/posix/Antarctica/South_Pole
	share/zoneinfo/posix/Antarctica/Vostok
	share/zoneinfo/posix/Antarctica/McMurdo
	share/zoneinfo/posix/Antarctica/Casey
	share/zoneinfo/posix/Antarctica/Mawson
	share/zoneinfo/posix/Antarctica/Davis
	share/zoneinfo/posix/Antarctica/Syowa
	share/zoneinfo/posix/Antarctica/Rothera
	share/zoneinfo/posix/HST
	share/zoneinfo/posix/Poland
	share/zoneinfo/posix/Canada
	share/zoneinfo/posix/Canada/Atlantic
	share/zoneinfo/posix/Canada/Eastern
	share/zoneinfo/posix/Canada/Central
	share/zoneinfo/posix/Canada/Mountain
	share/zoneinfo/posix/Canada/Yukon
	share/zoneinfo/posix/Canada/Pacific
	share/zoneinfo/posix/Canada/Saskatchewan
	share/zoneinfo/posix/Canada/East-Saskatchewan
	share/zoneinfo/posix/Canada/Newfoundland
	share/zoneinfo/posix/Mexico
	share/zoneinfo/posix/Mexico/General
	share/zoneinfo/posix/Mexico/BajaSur
	share/zoneinfo/posix/Mexico/BajaNorte
	share/zoneinfo/posix/EET
	share/zoneinfo/posix/MET
	share/zoneinfo/posix/Turkey
	share/zoneinfo/posix/Australia
	share/zoneinfo/posix/Australia/Eucla
	share/zoneinfo/posix/Australia/Sydney
	share/zoneinfo/posix/Australia/Tasmania
	share/zoneinfo/posix/Australia/Queensland
	share/zoneinfo/posix/Australia/Hobart
	share/zoneinfo/posix/Australia/Darwin
	share/zoneinfo/posix/Australia/Lindeman
	share/zoneinfo/posix/Australia/Adelaide
	share/zoneinfo/posix/Australia/Canberra
	share/zoneinfo/posix/Australia/LHI
	share/zoneinfo/posix/Australia/Perth
	share/zoneinfo/posix/Australia/North
	share/zoneinfo/posix/Australia/ACT
	share/zoneinfo/posix/Australia/Melbourne
	share/zoneinfo/posix/Australia/Currie
	share/zoneinfo/posix/Australia/Victoria
	share/zoneinfo/posix/Australia/Lord_Howe
	share/zoneinfo/posix/Australia/West
	share/zoneinfo/posix/Australia/Broken_Hill
	share/zoneinfo/posix/Australia/Brisbane
	share/zoneinfo/posix/Australia/Yancowinna
	share/zoneinfo/posix/Australia/South
	share/zoneinfo/posix/Australia/NSW
	share/zoneinfo/posix/GMT-0
	share/zoneinfo/posix/GMT
	share/zoneinfo/posix/Eire
	share/zoneinfo/posix/Cuba
	share/zoneinfo/posix/Portugal
	share/zoneinfo/posix/Iceland
	share/zoneinfo/posix/Kwajalein
	share/zoneinfo/posix/ROK
	share/zoneinfo/posix/GB-Eire
	share/zoneinfo/posix/Arctic
	share/zoneinfo/posix/Arctic/Longyearbyen
	share/zoneinfo/posix/CET
	share/zoneinfo/posix/CST6CDT
	share/zoneinfo/Mexico
	share/zoneinfo/Mexico/General
	share/zoneinfo/Mexico/BajaSur
	share/zoneinfo/Mexico/BajaNorte
	share/zoneinfo/EET
	share/zoneinfo/MET
	share/zoneinfo/Turkey
	share/zoneinfo/Australia
	share/zoneinfo/Australia/Eucla
	share/zoneinfo/Australia/Sydney
	share/zoneinfo/Australia/Tasmania
	share/zoneinfo/Australia/Queensland
	share/zoneinfo/Australia/Hobart
	share/zoneinfo/Australia/Darwin
	share/zoneinfo/Australia/Lindeman
	share/zoneinfo/Australia/Adelaide
	share/zoneinfo/Australia/Canberra
	share/zoneinfo/Australia/LHI
	share/zoneinfo/Australia/Perth
	share/zoneinfo/Australia/North
	share/zoneinfo/Australia/ACT
	share/zoneinfo/Australia/Melbourne
	share/zoneinfo/Australia/Currie
	share/zoneinfo/Australia/Victoria
	share/zoneinfo/Australia/Lord_Howe
	share/zoneinfo/Australia/West
	share/zoneinfo/Australia/Broken_Hill
	share/zoneinfo/Australia/Brisbane
	share/zoneinfo/Australia/Yancowinna
	share/zoneinfo/Australia/South
	share/zoneinfo/Australia/NSW
	share/zoneinfo/GMT-0
	share/zoneinfo/GMT
	share/zoneinfo/Eire
	share/zoneinfo/Cuba
	share/zoneinfo/Portugal
	share/zoneinfo/Iceland
	share/zoneinfo/Kwajalein
	share/zoneinfo/ROK
	share/zoneinfo/GB-Eire
	share/zoneinfo/Arctic
	share/zoneinfo/Arctic/Longyearbyen
	share/zoneinfo/CET
	share/zoneinfo/CST6CDT
	share/zoneinfo/localtime
EOF

unsquashfs -d "${USR}" -ef "${FILELIST}" "${USRFS}" 

popd

# populate usr/lib/systemd/system with the necessary static stuff
install -d -m 0755 "${ROOTDIR}/usr/lib/systemd/system"

function putunit {
	path="${ROOTDIR}/usr/lib/systemd/system/$1"
	cat > "${path}"
}

putunit default.target <<EOF
[Unit]
Description=Rocket apps target
DefaultDependencies=false
EOF

putunit sockets.target <<EOF
[Unit]
Description=Sockets
DefaultDependencies=false
EOF

putunit local-fs.target <<EOF
[Unit]
Description=Hook into early systemd for socket-activated systemd instances
DefaultDependencies=false
Requires=sockets.target
EOF

putunit exit-watcher.service <<EOF
[Unit]
Description=Graceful exit watcher
StopWhenUnneeded=true
DefaultDependencies=false

[Service]
ExecStart=/usr/bin/sleep 9999999999d 
ExecStopPost=/usr/bin/systemctl isolate reaper.service
EOF

putunit reaper.service <<EOF
[Unit]
Description=Rocket apps reaper
AllowIsolate=true
DefaultDependencies=false

[Service]
ExecStart=/reaper.sh
EOF

install -d -m 0755 "${ROOTDIR}/usr/lib/systemd/system/default.target.wants"
install -d -m 0755 "${ROOTDIR}/usr/lib/systemd/system/sockets.target.wants"

# simple reaper script for collecting the exit statuses of the apps
cat > "${ROOTDIR}/reaper.sh" <<-'EOF'
#!/usr/bin/bash
shopt -s nullglob

SYSCTL=/usr/bin/systemctl

cd /opt/stage2
for app in *; do 
        status=$(${SYSCTL} show --property ExecMainStatus "${app}.service")
        echo "${status#*=}" > "/rkt/status/$app"
done

${SYSCTL} halt --force
EOF
chmod 755 "${ROOTDIR}/reaper.sh"

# LD_PRELOAD shim to trick the sd_booted() "/run/systemd/system" check in systemd-nspawn
gcc -shared -fPIC -x c -pipe -Wl,--no-as-needed -ldl -o ${ROOTDIR}/fakesdboot.so - <<'EOF'
#define _GNU_SOURCE
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <dlfcn.h>

/* hack to make systemd-nspawn execute on non-sysd systems:
 * intercept lstat() so lstat of /run/systemd/system always succeeds and returns a directory
 */

static int (*libc_lxstat)(int, const char *, struct stat *);

static __attribute__((constructor)) void wrapper_init(void)
{
	libc_lxstat = dlsym(RTLD_NEXT, "__lxstat");
}

int __lxstat(int ver, const char *path, struct stat *stat)
{
	int ret = libc_lxstat(ver, path, stat);

	if(ret == -1 && !strcmp(path, "/run/systemd/system/")) {
		stat->st_mode = S_IFDIR;
		ret = 0;
	}

	return ret;
}
EOF

install -d "${ROOTDIR}/etc"
echo "rocket" > "${ROOTDIR}/etc/os-release"

# parent dir for the stage2 bind mounts
install -d "${ROOTDIR}/opt/stage2"

# dir for result code files
install -d "${ROOTDIR}/rkt/status"

# fin
mkdir "${BINDIR}"
tar cf "${BINDIR}/s1rootfs.tar" -C "${ROOTDIR}" .
OUTDIR=$(dirname "${OUTPUT}")
[ -d "$OUTDIR" ] || mkdir -p "${OUTDIR}"
go-bindata -o "${OUTPUT}" -prefix $(realpath "${BINDIR}") -pkg=stage1_rootfs "${BINDIR}"
rm -Rf "${WORK}"
